# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/122_leaf_temperature.ipynb.

# %% auto #0
__all__ = ['leaf_temperature']

# %% ../nbs/122_leaf_temperature.ipynb #b16c7f88
from .utils import latvap, satvap
from .parameter_classes import Atmos, PhysCon, Leaf, Flux

# %% ../nbs/122_leaf_temperature.ipynb #6ffe577f
def leaf_temperature(physcon: PhysCon, atmos: Atmos, leaf: Leaf, flux: Flux) -> Flux:
    """
    Calculate leaf temperature and energy fluxes.

    Solve the leaf energy balance using Newton-Raphson iteration to find the
    temperature that balances radiative forcing against longwave emission,
    sensible heat flux, and latent heat flux.

    __Parameters:__

    - PhysCon: Physical constants

        - tfrz: Freezing point of water (K).
        - mmh2o: Molecular mass of water (kg/mol).
        - sigma: Stefan-Boltzmann constant (W/m2/K4).

    - Atmos: Atmospheric forcing variables:

        - patm: Atmospheric pressure (Pa).
        - cpair: Specific heat of air at constant pressure (J/mol/K).
        - tair: Air temperature (K)
        - eair: Vapor pressure of air (Pa).

    - Leaf: Leaf parameters

        - emiss: Leaf emissivity (-).
        - tleaf: Leaf temperature (K). Used as initial guess on input

    - Flux: variables with the following inputs:

        - gbh: Leaf boundary layer conductance for heat (mol/m2 leaf/s).
        - gbv: Leaf boundary layer conductance for H2O (mol H2O/m2 leaf/s).
        - gs: Leaf stomatal conductance (mol H2O/m2 leaf/s).
        - qa: Leaf radiative forcing (W/m2 leaf).

    __Returns:__

    - Flux: Updated flux object with the following attributes:

        - tleaf: Leaf temperature (K). Updated to energy-balance solution on output.
        - rnet: Leaf net radiation (W/m2 leaf).
        - lwrad: Longwave radiation emitted from leaf (W/m2 leaf).
        - shflx: Leaf sensible heat flux (W/m2 leaf).
        - lhflx: Leaf latent heat flux (W/m2 leaf).
        - etflx: Leaf transpiration flux (mol H2O/m2 leaf/s).

    Parameters
    ----------
    physcon : PhysCon
        Physical constants:
        - tfrz : float
            Freezing point of water (K).
        - mmh2o : float
            Molecular mass of water (kg/mol).
        - sigma : float
            Stefan-Boltzmann constant (W/m2/K4).
    atmos : Atmos
        Atmospheric forcing variables:
        - patm : float
            Atmospheric pressure (Pa).
        - cpair : float
            Specific heat of air at constant pressure (J/mol/K).
        - tair : float
            Air temperature (K).
        - eair : float
            Vapor pressure of air (Pa).
    leaf : Leaf
        Leaf parameters:
        - emiss : float
            Leaf emissivity (-).
        - tleaf : float
            Leaf temperature (K). Used as initial guess on input

    flux : Flux
        Flux variables with the following inputs:
        - gbh : float
            Leaf boundary layer conductance for heat (mol/m2 leaf/s).
        - gbv : float
            Leaf boundary layer conductance for H2O (mol H2O/m2 leaf/s).
        - gs : float
            Leaf stomatal conductance (mol H2O/m2 leaf/s).
        - qa : float
            Leaf radiative forcing (W/m2 leaf).

    Returns
    -------
    flux : Flux
        Updated flux object with the following attributes:
        - tleaf : float
            Leaf temperature (K). Updated to energy-balance solution on output.
        - rnet : float
            Leaf net radiation (W/m2 leaf).
        - lwrad : float
            Longwave radiation emitted from leaf (W/m2 leaf).
        - shflx : float
            Leaf sensible heat flux (W/m2 leaf).
        - lhflx : float
            Leaf latent heat flux (W/m2 leaf).
        - etflx : float
            Leaf transpiration flux (mol H2O/m2 leaf/s).
    """

    # Latent heat of vaporization (J/mol)
    lambda_val = latvap(atmos.tair - physcon.tfrz, physcon.mmh2o)

    # Newton-Raphson iteration until leaf energy balance is less than
    # f0_max or to niter_max iterations
    niter = 0

    # Maximum number of iterations
    niter_max = 100

    # Maximum energy imbalance (W/m2)
    f0_max = 1e-06

    # Force entry into the while loop
    f0 = f0_max + 1.0

    # Newton-Raphson approach ---------------------------------------------------
    # While energy balance residual is larger than ~0, keep looping
    # By definition (Eq 10.13) the energy balance should be 0
    while abs(f0) > f0_max:
        niter += 1

        # Raise error if  iterations larger than 100
        if niter > niter_max:
            raise RuntimeError(
                f"leaf_temperature: failed to converge after {niter_max} iterations. "
                f"f0 = {f0:.6e}, tleaf = {flux.tleaf:.4f} K"
            )

        # Saturation vapor pressure (Pa) and temperature derivative (Pa/K)
        esat, desat = satvap(flux.tleaf - physcon.tfrz)

        # Leaf conductance for water vapor (mol H2O/m2/s)
        # (Eq.10.8)
        gleaf = flux.gs * flux.gbv / (flux.gs + flux.gbv)

        # Emitted longwave radiation (W/m2) and temperature derivative (W/m2/K)
        # (Eq.10.2)
        flux.lwrad = 2.0 * leaf.emiss * physcon.sigma * flux.tleaf**4
        dlwrad = 8.0 * leaf.emiss * physcon.sigma * flux.tleaf**3

        # Sensible heat flux (W/m2) and temperature derivative (W/m2/K)
        # (Eq 10.5)
        flux.shflx = 2.0 * atmos.cpair * (flux.tleaf - atmos.tair) * flux.gbh
        dshflx = 2.0 * atmos.cpair * flux.gbh

        # Latent heat flux (W/m2) and temperature derivative (W/m2/K)
        # (Eq.10.6)
        flux.lhflx = lambda_val / atmos.patm * (esat - atmos.eair) * gleaf
        dlhflx = lambda_val / atmos.patm * desat * gleaf

        # Energy balance residual (W/m2) and temperature derivative (W/m2/K)
        # (Eq. 10.13)
        f0 = flux.qa - flux.lwrad - flux.shflx - flux.lhflx
        df0 = -dlwrad - dshflx - dlhflx

        # Change in leaf temperature
        # (Eq 10.14)
        dtleaf = -f0 / df0

        # Update leaf temperature
        flux.tleaf = flux.tleaf + dtleaf

    # Net radiation
    flux.rnet = flux.qa - flux.lwrad

    # Error check ---------------------------------------------------------------
    err = flux.rnet - flux.shflx - flux.lhflx
    if abs(err) > f0_max:
        print(f"err = {err:15.3f}")
        print(f"qa = {flux.qa:15.3f}")
        print(f"lwrad = {flux.lwrad:15.3f}")
        print(f"sh = {flux.shflx:15.3f}")
        print(f"lh = {flux.lhflx:15.3f}")
        raise RuntimeError("leaf_temperature: energy balance not closed")

    # Water vapor flux: W/m2 -> mol H2O/m2/s
    flux.etflx = flux.lhflx / lambda_val

    return flux
