# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/124_leaf_phosynthesis.ipynb.

# %% auto #0
__all__ = ['leaf_photosynthesis']

# %% ../nbs/124_leaf_phosynthesis.ipynb #b16c7f88
import numpy as np
from .leaf_ci_optimization import leaf_ci_optimization
from .parameter_classes import Atmos, Leaf, Flux, PhysCon
from .utils import satvap, arrhenius_function, inhibition_function

# %% ../nbs/124_leaf_phosynthesis.ipynb #6ffe577f
def leaf_photosynthesis(physcon: PhysCon, atmos: Atmos, leaf: Leaf, flux: Flux) -> Flux:
    """
    Calculate leaf photosynthesis for a specified stomatal conductance.

    Temperature-adjust photosynthetic parameters using the Arrhenius function
    (Equation 11.34) and peaked Arrhenius function (Equations 11.35–11.36).
    
    Calculate the electron transport rate (Equation 11.21), then compute
    gross and net photosynthesis and intercellular CO2 via
    ``leaf_ci_optimization``. This routine is used with the water-use
    efficiency (WUE) stomatal optimization.

    For C3 plants, temperature adjustment uses the Arrhenius function
    (Equation 11.34) for Kc, Ko, and Γ*, and the peaked Arrhenius
    function (Equations 11.35–11.36) for Vcmax, Jmax, and Rd. The
    electron transport rate J is the smaller root of the co-limitation
    quadratic (Equation 11.21) between the light utilization rate
    I_PSII = 0.5 · Φ_PSII · APAR and Jmax.

    For C4 plants, temperature adjustment follows the Q10 formulation
    with high- and low-temperature stress factors (Equations 11.72–11.74).

    After temperature adjustment, ``leaf_ci_optimization`` is called to
    compute photosynthetic rates and intercellular CO2.

    __Parameters:__

    - PhysCon: Physical constants:

        - tfrz: Freezing point of water (K).
        - rgas: Universal gas constant (J/K/mol).

     - Atmos: Atmospheric forcing variables:

        - co2air: Atmospheric CO2 concentration (umol/mol).
        - eair: Vapor pressure of air (Pa).

     - Leaf: Leaf physiological parameters:

        - Photosynthetic pathway and co-limitation:

            - c3psn: Photosynthetic pathway: 1 = C3, 0 = C4 plant.

        - Rates at 25°C:

            - vcmax25: Maximum carboxylation rate at 25°C (umol/m2/s).
            - jmax25: Maximum electron transport rate at 25°C (umol/m2/s).
            - rd25: Leaf respiration rate at 25°C (umol CO2/m2/s).

        - Michaelis-Menten constants at 25°C:

            - kc25: Michaelis-Menten constant for CO2 at 25°C (umol/mol).
            - ko25: Michaelis-Menten constant for O2 at 25°C (mmol/mol).
            - cp25: CO2 compensation point at 25°C (umol/mol).

        - Activation energies (J/mol):

            - kcha, koha, cpha: Activation energies for Kc, Ko, and Γ* respectively.
            - vcmaxha, jmaxha, rdha: Activation energies for Vcmax, Jmax, and Rd respectively.

        - Deactivation energies (J/mol):
            - vcmaxhd, jmaxhd, rdhd: Deactivation energies for Vcmax, Jmax, and Rd respectively.

        - Entropy terms (J/mol/K):
            - vcmaxse, jmaxse, rdse: Entropy terms for Vcmax, Jmax, and Rd respectively.

        - Scaling factors for high temperature inhibition (1.0 at 25°C):
            - vcmaxc, jmaxc, rdc: Scaling factors for Vcmax, Jmax, and Rd respectively.

        - Electron transport:
            - phi_psii: Quantum yield of photosystem II (mol/mol).
            - theta_j: Empirical curvature parameter for electron transport rate (-).

        - C4-specific:
            - kp25_c4: Initial slope of CO2 response curve at 25°C (mol/m2/s).

    - Flux: Flux variables with the following inputs:

        - gbv: Leaf boundary layer conductance for H2O (mol H2O/m2 leaf/s).
        - gbc: Leaf boundary layer conductance for CO2 (mol CO2/m2 leaf/s).
        - apar: Leaf absorbed PAR (umol photon/m2 leaf/s).
        - tleaf: Leaf temperature (K).
        - gs: Leaf stomatal conductance (mol H2O/m2 leaf/s).

    __Returns:__

    - Flux: Updated flux object with the following attributes:

        - Temperature-adjusted parameters:

            - vcmax: Maximum carboxylation rate (umol/m2/s).
            - jmax: Maximum electron transport rate (umol/m2/s).
            - cp: CO2 compensation point (umol/mol).
            - kc: Michaelis-Menten constant for CO2 (umol/mol).
            - ko: Michaelis-Menten constant for O2 (mmol/mol).
            - je: Electron transport rate (umol/m2/s).
            - kp_c4: C4 initial slope of CO2 response curve (mol/m2/s).
            - rd: Leaf respiration rate (umol CO2/m2 leaf/s).

        - Photosynthetic rates:

            - ac: Rubisco-limited gross photosynthesis (umol CO2/m2 leaf/s).
            - aj: RuBP regeneration-limited gross photosynthesis (umol CO2/m2 leaf/s).
            - ap: Product-limited (C3) or CO2-limited (C4) gross photosynthesis (umol CO2/m2 leaf/s).
            - ag: Leaf gross photosynthesis (umol CO2/m2 leaf/s).
            - an: Leaf net photosynthesis (umol CO2/m2 leaf/s).

        - Leaf surface gas exchange:

            - cs: Leaf surface CO2 concentration (umol/mol).
            - ci: Leaf intercellular CO2 concentration (umol/mol).
            - hs: Leaf fractional humidity at surface (-).
            - vpd: Leaf vapor pressure deficit at surface (Pa).

    Parameters
    ----------
    physcon : PhysCon
        Physical constants:
        - tfrz : float
            Freezing point of water (K).
        - rgas : float
            Universal gas constant (J/K/mol).
    atmos : Atmos
        Atmospheric forcing variables:
        - co2air : float
            Atmospheric CO2 concentration (umol/mol).
        - eair : float
            Vapor pressure of air (Pa).
    leaf : Leaf
        Leaf physiological parameters:

        Photosynthetic pathway and co-limitation:
        - c3psn : int
            Photosynthetic pathway: 1 = C3, 0 = C4 plant.

        Rates at 25°C:
        - vcmax25 : float
            Maximum carboxylation rate at 25°C (umol/m2/s).
        - jmax25 : float
            Maximum electron transport rate at 25°C (umol/m2/s).
        - rd25 : float
            Leaf respiration rate at 25°C (umol CO2/m2/s).

        Michaelis-Menten constants at 25°C:
        - kc25 : float
            Michaelis-Menten constant for CO2 at 25°C (umol/mol).
        - ko25 : float
            Michaelis-Menten constant for O2 at 25°C (mmol/mol).
        - cp25 : float
            CO2 compensation point at 25°C (umol/mol).

        Activation energies (J/mol):
        - kcha, koha, cpha : float
            Activation energies for Kc, Ko, and Γ* respectively.
        - vcmaxha, jmaxha, rdha : float
            Activation energies for Vcmax, Jmax, and Rd respectively.

        Deactivation energies (J/mol):
        - vcmaxhd, jmaxhd, rdhd : float
            Deactivation energies for Vcmax, Jmax, and Rd respectively.

        Entropy terms (J/mol/K):
        - vcmaxse, jmaxse, rdse : float
            Entropy terms for Vcmax, Jmax, and Rd respectively.

        Scaling factors for high temperature inhibition (1.0 at 25°C):
        - vcmaxc, jmaxc, rdc : float
            Scaling factors for Vcmax, Jmax, and Rd respectively.

        Electron transport:
        - phi_psii : float
            Quantum yield of photosystem II (mol/mol).
        - theta_j : float
            Empirical curvature parameter for electron transport rate (-).

        C4-specific:
        - kp25_c4 : float
            Initial slope of CO2 response curve at 25°C (mol/m2/s).
    flux : Flux
        Flux variables with the following inputs:
        - gbv : float
            Leaf boundary layer conductance for H2O (mol H2O/m2 leaf/s).
        - gbc : float
            Leaf boundary layer conductance for CO2 (mol CO2/m2 leaf/s).
        - apar : float
            Leaf absorbed PAR (umol photon/m2 leaf/s).
        - tleaf : float
            Leaf temperature (K).
        - gs : float
            Leaf stomatal conductance (mol H2O/m2 leaf/s).

    Returns
    -------
    flux : Flux
        Updated flux object with the following attributes:

        Temperature-adjusted parameters:
        - vcmax : float
            Maximum carboxylation rate (umol/m2/s).
        - jmax : float
            Maximum electron transport rate (umol/m2/s).
        - cp : float
            CO2 compensation point (umol/mol).
        - kc : float
            Michaelis-Menten constant for CO2 (umol/mol).
        - ko : float
            Michaelis-Menten constant for O2 (mmol/mol).
        - je : float
            Electron transport rate (umol/m2/s).
        - kp_c4 : float
            C4 initial slope of CO2 response curve (mol/m2/s).
        - rd : float
            Leaf respiration rate (umol CO2/m2 leaf/s).

        Photosynthetic rates:
        - ac : float
            Rubisco-limited gross photosynthesis (umol CO2/m2 leaf/s).
        - aj : float
            RuBP regeneration-limited gross photosynthesis
            (umol CO2/m2 leaf/s).
        - ap : float
            Product-limited (C3) or CO2-limited (C4) gross
            photosynthesis (umol CO2/m2 leaf/s).
        - ag : float
            Leaf gross photosynthesis (umol CO2/m2 leaf/s).
        - an : float
            Leaf net photosynthesis (umol CO2/m2 leaf/s).

        Leaf surface gas exchange:
        - cs : float
            Leaf surface CO2 concentration (umol/mol).
        - ci : float
            Leaf intercellular CO2 concentration (umol/mol).
        - hs : float
            Leaf fractional humidity at surface (-).
        - vpd : float
            Leaf vapor pressure deficit at surface (Pa).
    """

    # Adjust photosynthetic parameters for temperature 
    # Matlab ft() == to arrhenius_fucntion()
    # Matlab fth() == to inhibition_function()

    # C3 temperature response ---------------------------------------------------
    if leaf.c3psn == 1:

        # Rubisco kinetics Eq 11.34
        # Describe binding affinities that increase monotonically with
        # temperature. This model describes that at high temperature Rubisco
        # becomes less effiecint at getting CO2 (HIGH Km)
        
        # The parameters represent how hungry it is for CO2 (Kc), how distracted
        # it is by O2 (Ko), and the CO2 level at which photosynthesis and
        # photorespiration exactly cancel out (Γ*). Table 11.2 pp 173.
        
        # Remember Kc is a concentration
        # High Kc means it needs more substrate (CO2) to achive the 50%
        flux.kc = leaf.kc25 * arrhenius_function(tl=flux.tleaf, ha=leaf.kcha)
        
        # As Ko increases at high temperatures the ratio 02/ko gets smaller, 
        # meaning that co2 is fixed more slightly easer
        flux.ko = leaf.ko25 * arrhenius_function(tl=flux.tleaf, ha=leaf.koha)
        flux.cp = leaf.cp25 * arrhenius_function(tl=flux.tleaf, ha=leaf.cpha)

        # Maximum Carboxilation rate (Vcmax) peaked Arrhenius (Eq 11.35)
        # Represent how fast Rubisco can work at full capacity
        t1 = arrhenius_function(tl=flux.tleaf, ha=leaf.vcmaxha)
        t2 = inhibition_function(flux.tleaf, leaf.vcmaxhd, leaf.vcmaxse, leaf.vcmaxc)
        flux.vcmax = leaf.vcmax25 * t1 * t2

        # Electron transport rate (Jmax) peaked Arrhenius (Eq 11.35)
        # Jmax has a lower activation energy than Vcmax (43,540 vs 65,330 J/mol
        # from Table 11.2), meaning it's less sensitive to warming.
        # The electron transport chain is more thermally stable than Rubisco.
        t1 = arrhenius_function(tl=flux.tleaf, ha=leaf.jmaxha)
        t2 = inhibition_function(flux.tleaf, leaf.jmaxhd, leaf.jmaxse, leaf.jmaxc)
        
        # Eq 11.35. The product t1*t2 creates the peaked curve
        flux.jmax = leaf.jmax25 * t1 * t2

        # Respiration (Rd) peaked Arrhenius (Equation 11.35 applied to Rd) 
        # Even while photosynthesizing, the leaf burns some sugar for its own
        # energy needs. This cost also follows the peaked Arrhenius response.
        # Leaf respiration represent the leaf "maintenance cost"
        
        # Increase the rate up 
        t1 = arrhenius_function(tl=flux.tleaf, ha=leaf.rdha)
        
        # Bring the rate down at high temperatures
        t2 = inhibition_function(flux.tleaf, leaf.rdhd, leaf.rdse, leaf.rdc)
        
        # The product t1*t2 creates the peaked curve
        flux.rd = leaf.rd25 * t1 * t2

        flux.kp_c4 = 0.0

    # C4 temperature response ---------------------------------------------------
    else:
        
        # Implementation of Equation (11.72) from the textbook. 
        # Instead of the arrhenius function, C4 plants use a Q10 formulation 
        # with explicit stress factors.

        # Q10 = 2: the basic "warmer = faster" effect (rate doubles every 10°C)
        t1 = 2.0 ** ((flux.tleaf - (physcon.tfrz + 25)) / 10.0)

        # Low-temperature stress: a penalty that kicks in below 15°C
        # (s3 = 0.2, s4 = 288.15 K)
        t2 = 1.0 + np.exp(0.2 * ((physcon.tfrz + 15) - flux.tleaf))

        # High-temperature stress: a penalty that kicks in above 40°C
        # (s1 = 0.3, s2 = 313.15 K)
        t3 = 1.0 + np.exp(0.3 * (flux.tleaf - (physcon.tfrz + 40)))
        
        flux.vcmax = leaf.vcmax25 * t1 / (t2 * t3)

        # Respiration for C4 follows Equation (11.73) with high-temperature
        # stress above 55°C, and kp (the PEP carboxylase slope) follows
        # Equation (11.74) with Q10 = 2 and no stress factors.
        t3 = 1.0 + np.exp(1.3 * (flux.tleaf - (physcon.tfrz + 55)))
        
        flux.rd = leaf.rd25 * t1 / t3

        flux.kp_c4 = leaf.kp25_c4 * t1

        flux.kc = 0.0
        flux.ko = 0.0
        flux.cp = 0.0
        flux.jmax = 0.0
        flux.je = 0.0

    # Electron transport rate for C3 plants 
    # Solve the polynomial: aquad*Je^2 + bquad*Je + cquad = 0 for Je.
    # Correct solution is the smallest of the two roots.
    # This solves Equation (11.21)
    # The quadratic with curvature parameter Θ_J creates a smooth transition
    # between these two limits, as shown in Figure 11.5a.

    if leaf.c3psn == 1:
        qabs = 0.5 * leaf.phi_psii * flux.apar
        aquad = leaf.theta_j
        bquad = -(qabs + flux.jmax)
        cquad = qabs * flux.jmax
        roots = np.roots([aquad, bquad, cquad])
        flux.je = min(roots.real)

    # Photosythesis and Ci calculation ------------------------------------------
    # Calculate photosynthesis for a specified stomatal conductance
    # With all parameters temperature-adjusted and J calculated, calculate
    # photosynthesis and intercellular CO2
    flux = leaf_ci_optimization(atmos, leaf, flux)

    # Relative humidity and vapor pressure at leaf surface ----------------------
    # This calculates the humidity right at the leaf surface, a weighted average
    # between the dry outside air (eair, pulled through the boundary layer with
    # conductance gbv) and the saturated air inside the leaf (esat, pushed out
    # through stomata with conductance gs).

    # The vapor pressure deficit (VPD) at the leaf surface is important because
    # it feeds back into stomatal conductance models
    esat, desat = satvap(flux.tleaf - physcon.tfrz)
    flux.hs = (flux.gbv * atmos.eair + flux.gs * esat) / ((flux.gbv + flux.gs) * esat)
    flux.vpd = max(esat - flux.hs * esat, 0.1)

    # Diffusion equation error check --------------------------------------------
    # Compare with diffusion equation: An = (ca - ci) * gleaf
    an_err = (atmos.co2air - flux.ci) / (1.0 / flux.gbc + 1.6 / flux.gs)
    
    if flux.an > 0 and abs(flux.an - an_err) > 0.01:
        print(f"An = {flux.an:15.4f}")
        print(f"An_err = {an_err:15.4f}")
        raise RuntimeError("leaf_photosynthesis(): failed diffusion error check")

    return flux
