# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/100_parameter_classes.ipynb.

# %% auto #0
__all__ = ['Params', 'PhysCon', 'Atmos', 'Ground', 'Soil', 'RootVar', 'Leaf', 'Flux', 'SurEauVegetationParams',
           'SurEauSoilParams', 'SurEauComputationOptions', 'SurEauModelOptions', 'SurEauPlantState',
           'SurEauPlantFluxes', 'SurEauPlantDiagnostics', 'SurEauSoil', 'SurEauClimate', 'SurEauClimateHourly']

# %% ../nbs/100_parameter_classes.ipynb #854dbece
import numpy as np
from dataclasses import dataclass, field
from typing import List, Literal, Optional

# %% ../nbs/100_parameter_classes.ipynb #b16c7f88
@dataclass
class Params:
    """Object holding  Waveband indices

    - vis: Index for visible radiation
    - nir: Index for near-infrared radiation
    """

    vis: int = 0  # Index for visible radiation
    nir: int = 1  # Index for near-infrared radiation

# %% ../nbs/100_parameter_classes.ipynb #0ef43a87
@dataclass
class PhysCon:
    """Object holding Physical constants

    - grav:  Gravitational acceleration (m/s2)
    - tfrz:  Freezing point of water (K)
    - sigma: Stefan-Boltzmann constant (W/m2/K4)
    - mmdry: Molecular mass of dry air (kg/mol)
    - mmh2o: Molecular mass of water (kg/mol)
    - cpd:   Specific heat of dry air at constant pressure (J/kg/K)
    - cpw:   Specific heat of water vapor at constant pressure (J/kg/K)
    - rgas:  Universal gas constant (J/K/mol)
    - visc0: Kinematic viscosity at 0C and 1013.25 hPa (m2/s)
    - Dh0:   Molecular diffusivity (heat) at 0C and 1013.25 hPa (m2/s)
    - Dv0:   Molecular diffusivity (H2O) at 0C and 1013.25 hPa (m2/s)
    - Dc0:   Molecular diffusivity (CO2) at 0C and 1013.25 hPa (m2/s)
    - denh2o: Density of liquid water (kg/m3)
    """

    # Gravitational acceleration (m/s2)
    grav: float = 9.80665

    # Freezing point of water (K)
    tfrz: float = 273.15

    # Stefan-Boltzmann constant (W/m2/K4)
    sigma: float = 5.67e-08

    # Molecular mass of dry air (kg/mol)
    mmdry: float = 28.97e-03

    # Molecular mass of water (kg/mol)
    mmh2o: float = 18.02e-03

    # Specific heat of dry air at constant pressure (J/kg/K)
    cpd: float = 1005.0

    # Specific heat of water vapor at constant pressure (J/kg/K)
    cpw: float = 1846.0

    # Universal gas constant (J/K/mol)
    rgas: float = 8.31446

    # Kinematic viscosity at 0C and 1013.25 hPa (m2/s)
    visc0: float = 13.3e-06

    # Molecular diffusivity (heat) at 0C and 1013.25 hPa (m2/s)
    Dh0: float = 18.9e-06

    # Molecular diffusivity (H2O) at 0C and 1013.25 hPa (m2/s)
    Dv0: float = 21.8e-06

    # Molecular diffusivity (CO2) at 0C and 1013.25 hPa (m2/s)
    Dc0: float = 13.8e-06

    # Density of liquid water (kg/m3)
    denh2o: float = 1000.0

# %% ../nbs/100_parameter_classes.ipynb #0db2f047
@dataclass
class Atmos:
    """Object holding Atmospheric forcing variables

    - co2air: Atmospheric CO2 (umol/mol)
    - o2air:  Atmospheric O2 (mmol/mol)
    - tair:   Air temperature (K)
    - relhum: Relative humidity (%)
    - eair:   Vapor pressure of air (Pa)
    - qair:   Specific humidity (kg/kg)
    - wind:   Wind speed (m/s)
    - patm:   Atmospheric pressure (Pa)
    - rhomol: Molar density (mol/m3)
    - rhoair: Air density (kg/m3)
    - mmair:  Molecular mass of air (kg/mol)
    - cpair:  Specific heat of air at constant pressure (J/mol/K)
    - irsky:  Atmospheric longwave radiation (W/m2)
    - swsky:  Solar radiation by waveband (W/m2)
    """

    # Atmospheric CO2 (umol/mol)
    co2air: float = 0.0

    # Atmospheric O2 (mmol/mol)
    o2air: float = 0.0

    # Air temperature (K)
    tair: float = 0.0

    # Relative humidity (%)
    relhum: float = 0.0

    # Vapor pressure of air (Pa)
    eair: float = 0.0

    # Specific humidity (kg/kg)
    qair: float = 0.0

    # Wind speed (m/s)
    wind: float = 0.0

    # Atmospheric pressure (Pa)
    patm: float = 0.0

    # Molar density (mol/m3)
    rhomol: float = 0.0

    # Air density (kg/m3)
    rhoair: float = 0.0

    # Molecular mass of air (kg/mol)
    mmair: float = 0.0

    # Specific heat of air at constant pressure (J/mol/K)
    cpair: float = 0.0

    # Atmospheric longwave radiation (W/m2)
    irsky: float = 0.0

    # Solar radiation by waveband (W/m2)
    swsky: list = field(default_factory=lambda: [0.0, 0.0])

# %% ../nbs/100_parameter_classes.ipynb #ba2b0f56
@dataclass
class Ground:
    """Object holding Ground surface variables

    - albsoi: Soil albedo [vis, nir]
    - irgrd: Ground longwave radiation (W/m2)
    """

    # Soil albedo [vis, nir]
    albsoi: list = field(default_factory=lambda: [0.0, 0.0])

    # Ground longwave radiation (W/m2)
    irgrd: float = 0.0

# %% ../nbs/100_parameter_classes.ipynb #5492103c
@dataclass
class Soil:
    """Object holding Soil parameters and state variables

    - texture: Soil texture class
    - nlevsoi: Number of soil layers
    - dz: Soil layer thickness (m)
    - rootfr: Fraction of roots in each soil layer
    - watsat: Volumetric water content at saturation (porosity)
    - psisat: Matric potential at saturation (mm)
    - hksat: Hydraulic conductivity at saturation (mm H2O/s)
    - bsw: Clapp and Hornberger "b" parameter
    - h2osoi_vol: Volumetric water content (m3/m3)
    - psi: Matric potential (mm)
    """

    # Soil texture class
    texture: int = 5

    # Number of soil layers
    nlevsoi: int = 0

    # Soil layer thickness (m)
    dz: list = field(default_factory=list)

    # Fraction of roots in each soil layer
    rootfr: list = field(default_factory=list)

    # Volumetric water content at saturation (porosity)
    watsat: list = field(default_factory=list)

    # Matric potential at saturation (mm)
    psisat: list = field(default_factory=list)

    # Hydraulic conductivity at saturation (mm H2O/s)
    hksat: list = field(default_factory=list)

    # Clapp and Hornberger "b" parameter
    bsw: list = field(default_factory=list)

    # Volumetric water content (m3/m3)
    h2osoi_vol: list = field(default_factory=list)

    # Matric potential (mm)
    psi: list = field(default_factory=list)

# %% ../nbs/100_parameter_classes.ipynb #62f80583
@dataclass
class RootVar:
    """Object holding Fine root parameters

    - radius: Fine root radius (m)
    - density: Fine root density (g biomass / m3 root)
    - resist: Hydraulic resistivity of root tissue (MPa.s.g/mmol H2O)
    - biomass: Fine root biomass (g biomass / m2)
    """

    # Fine root radius (m)
    radius: float = 0.0

    # Fine root density (g biomass / m3 root)
    density: float = 0.0

    # Hydraulic resistivity of root tissue (MPa.s.g/mmol H2O)
    resist: float = 0.0

    # Fine root biomass (g biomass / m2)
    biomass: float = 0.0

# %% ../nbs/100_parameter_classes.ipynb #93a37643
@dataclass
class Leaf:
    """Object holding Leaf physiological and structural parameters

    - c3psn: Photosynthetic pathway: 1 = C3, 0 = C4
    - colim: Photosynthesis co-limitation: 0 = no, 1 = yes
    - vcmax25: Maximum carboxylation rate at 25C (umol/m2/s)
    - jmax25: Maximum electron transport rate at 25C (umol/m2/s)
    - rd25: Leaf respiration rate at 25C (umol CO2/m2/s)
    - kc25: Michaelis-Menten constant for CO2 at 25C (umol/mol)
    - ko25: Michaelis-Menten constant for O2 at 25C (mmol/mol)
    - cp25: CO2 compensation point at 25C (umol/mol)
    - kcha: Activation energy for Kc (J/mol)
    - koha: Activation energy for Ko (J/mol)
    - cpha: Activation energy for Cp (J/mol)
    - vcmaxha: Activation energy for Vcmax (J/mol)
    - jmaxha: Activation energy for Jmax (J/mol)
    - rdha:  Activation energy for Rd (J/mol)
    - vcmaxhd: Deactivation energy for Vcmax (J/mol)
    - jmaxhd:  Deactivation energy for Jmax (J/mol)
    - rdhd:  Deactivation energy for Rd (J/mol)
    - vcmaxse: Entropy term for Vcmax (J/mol/K)
    - jmaxse: Entropy term for Jmax (J/mol/K)
    - rdse: Entropy term for Rd (J/mol/K)
    - vcmaxc: Vcmax scaling factor for high temperature inhibition
    - jmaxc:  Jmax scaling factor for high temperature inhibition
    - rdc:  Rd scaling factor for high temperature inhibition
    - phi_psii: Quantum yield of PS II
    - theta_j: Empirical curvature parameter for electron transport rate
    - colim_c3: Empirical curvature parameter for C3 co-limitation
    - colim_c4a:  Empirical curvature parameter for C4 co-limitation
    - colim_c4b:  Empirical curvature parameter for C4 co-limitation
    - qe_c4: C4: Quantum yield (mol CO2 / mol photons)
    - kp25_c4: C4: Initial slope of CO2 response curve at 25C (mol/m2/s)
    - dleaf: Leaf dimension (m)
    - emiss: Leaf emissivity
    - rho: Leaf reflectance [vis, nir]
    - tau: Leaf transmittance [vis, nir]
    - iota: Stomatal efficiency (umol CO2/ mol H2O)
    - capac: Plant capacitance (mmol H2O/m2 leaf area/MPa)
    - minl_wp: Minimum leaf water potential (MPa)
    - gplant: Stem (xylem-to-leaf) hydraulic conductance (mmol H2O/m2 leaf area/s/MPa)
    - g0: Minimum Conductance (mol/m2/s)
    - g1_medlyn: Medlyn slope parameter (kPa^0.5). Controls stomatal sensitivity to VPD. Higher g1 = less conservative.
    - stomatal_model: Stomatal model to use "optimization", "medlyn" or "profit_max"
    - a_psi: Parameter that controls the steepness of this curve in the "profit_max" model
    - psi_50: Water potential at 50% loss of conductance (MPa). Always < 0.
    """

    # Photosynthetic pathway: 1 = C3, 0 = C4
    c3psn: int = 1

    # Photosynthesis co-limitation: 0 = no, 1 = yes
    colim: int = 1

    # Maximum carboxylation rate at 25C (umol/m2/s)
    vcmax25: float = 0.0

    # Maximum electron transport rate at 25C (umol/m2/s)
    jmax25: float = 0.0

    # Leaf respiration rate at 25C (umol CO2/m2/s)
    rd25: float = 0.0

    # Michaelis-Menten constant for CO2 at 25C (umol/mol)
    kc25: float = 0.0

    # Michaelis-Menten constant for O2 at 25C (mmol/mol)
    ko25: float = 0.0

    # CO2 compensation point at 25C (umol/mol)
    cp25: float = 0.0

    # Activation energy for Kc (J/mol)
    kcha: float = 0.0

    # Activation energy for Ko (J/mol)
    koha: float = 0.0

    # Activation energy for Cp (J/mol)
    cpha: float = 0.0

    # Activation energy for Vcmax (J/mol)
    vcmaxha: float = 0.0

    # Activation energy for Jmax (J/mol)
    jmaxha: float = 0.0

    # Activation energy for Rd (J/mol)
    rdha: float = 0.0

    # Deactivation energy for Vcmax (J/mol)
    vcmaxhd: float = 0.0

    # Deactivation energy for Jmax (J/mol)
    jmaxhd: float = 0.0

    # Deactivation energy for Rd (J/mol)
    rdhd: float = 0.0

    # Entropy term for Vcmax (J/mol/K)
    vcmaxse: float = 0.0

    # Entropy term for Jmax (J/mol/K)
    jmaxse: float = 0.0

    # Entropy term for Rd (J/mol/K)
    rdse: float = 0.0

    # Vcmax scaling factor for high temperature inhibition
    vcmaxc: float = 0.0

    # Jmax scaling factor for high temperature inhibition
    jmaxc: float = 0.0

    # Rd scaling factor for high temperature inhibition
    rdc: float = 0.0

    # Quantum yield of PS II
    phi_psii: float = 0.0

    # Empirical curvature parameter for electron transport rate
    theta_j: float = 0.0

    # Empirical curvature parameter for C3 co-limitation
    colim_c3: float = 0.0

    # Empirical curvature parameter for C4 co-limitation
    colim_c4a: float = 0.0

    # Empirical curvature parameter for C4 co-limitation
    colim_c4b: float = 0.0

    # C4: Quantum yield (mol CO2 / mol photons)
    qe_c4: float = 0.0

    # C4: Initial slope of CO2 response curve at 25C (mol/m2/s)
    kp25_c4: float = 0.0

    # Leaf dimension (m)
    dleaf: float = 0.0

    # Leaf emissivity
    emiss: float = 0.0

    # Leaf reflectance [vis, nir]
    rho: list = field(default_factory=lambda: [0.0, 0.0])

    # Leaf transmittance [vis, nir]
    tau: list = field(default_factory=lambda: [0.0, 0.0])

    # Stomatal efficiency (umol CO2/ mol H2O)
    iota: float = 0.0

    # Plant capacitance (mmol H2O/m2 leaf area/MPa)
    capac: float = 0.0

    # Minimum leaf water potential (MPa)
    minl_wp: float = 0.0

    # Stem (xylem-to-leaf) hydraulic conductance (mmol H2O/m2 leaf area/s/MPa)
    gplant: float = 0.0

    # Which stomatal model to use:
    #   "optimization" = original WUE optimization from Bonan Ch. 13
    #                    (uses brent_root + stomata_efficiency)
    #   "medlyn"       = Medlyn et al. (2011) empirical model
    #                    (uses iterative gs-An coupling + hard hydraulic cap)
    #   "profit_max"   = Medlyn + Sperry profit-maximisation framework
    #                    (uses gs sweep + gain-cost optimisation)
    stomatal_model: Literal["optimization", "medlyn", "profit_max"] = "optimization"

    # Minimum stomatal conductance (mol H2O/m2/s).
    # The residual conductance when An = 0 (e.g., at night).
    # Example values:
    #   Broadleaf trees: 0.01 mol/m2/s
    #   Conifers:        0.005 mol/m2/s
    #   Crops:           0.02 mol/m2/s
    g0: float = 0.01

    # Medlyn slope parameter (kPa^0.5).
    # Controls stomatal sensitivity to VPD. Higher g1 = less conservative.
    # Example values from:
    #   Tropical broadleaf evergreen: 3.77 kPa^0.5
    #   Temperate broadleaf deciduous: 4.45 kPa^0.5
    #   Needleleaf evergreen:          2.35 kPa^0.5
    #   C3 crops/grasses:              5.79 kPa^0.5
    #   C4 crops/grasses:              1.62 kPa^0.5
    g1_medlyn: float = 4.0

    # PROFIT-MAX: Vulnerability curve shape parameter
    #
    # WHY: The profit-maximisation model needs a vulnerability curve that
    # describes how hydraulic conductance declines with water potential.
    # The a_psi parameter controls the steepness of this curve.

    # Low a_psi (2-3): Represents a gentle curve, therefore conductance loss
    # begins early and spreads over a wide psi range. Represents species that
    # close stomata cautiously to avoid any damage.

    # High a_psi (5-8): Represents a steep curve, therefore conductance is
    # maintained until psi is very close to minl_wp, then drops sharply.
    # Represents a species that tolerate more stress.

    # Default 4: A moderate steepness suitable for a "typical" broadleaf tree.
    #
    # Note: Only used when stomatal_model = "profit_max".
    #   Ignored by "optimization" and "medlyn" models.
    a_psi: float = 4.0

    # PROFIT-MAX: Water potential at 50% loss of hydraulic conductance (MPa).
    #
    # This is the TRUE P50 of the vulnerability curve — a separate plant trait
    # from minl_wp (the critical/minimum safe psi).
    #
    # Distinction:
    #   psi_50  = where 50% of conductance is lost. Controls the SHAPE of the
    #             cost function. Species with more negative psi_50 tolerate
    #             drier conditions before losing conductance.
    #   minl_wp = the hard safety threshold. Beyond this, cavitation is lethal.
    #             Typically near P88–P95.
    #
    # Typical values (temperate broadleaf):
    #   psi_50  ≈ -2.5 MPa  (moderate vulnerability, e.g. Quercus robur)
    #   minl_wp ≈ -3.0 MPa  (safety margin: ~0.5 MPa above psi_50)
    #
    # Rule of thumb: minl_wp should be 1.5–2× more negative than psi_50.
    # If psi_50 = minl_wp, cost at the safety threshold is always 0.5 by
    # construction — the model becomes too permissive.
    #
    # Note: Only used when stomatal_model = "profit_max".
    psi_50: float = -2.5

# %% ../nbs/100_parameter_classes.ipynb #b992728a
@dataclass
class Flux:
    """Object holding Flux variables (state and output)

    - __Site / canopy__

        - height: Leaf height (m)
        - lai: Canopy leaf area index (m2/m2)

    - __Hydraulics__

        - rplant: Aboveground plant stem resistance (MPa.s.m2/mmol H2O)
        - rsoil: Soil hydraulic resistance (MPa.s.m2/mmol H2O)
        - lsc: Leaf-specific conductance (mmol H2O/m2 leaf/s/MPa)
        - psi_soil: Weighted soil water potential (MPa)
        - psi_leaf: Leaf water potential (MPa)
        - et_loss: Fraction of transpiration from each soil layer

    - __Radiation__

        - swinc: Incident solar radiation on leaf [vis, nir]
        - swflx: Absorbed solar radiation [vis, nir]
        - apar: Absorbed PAR (umol photon/m2 leaf/s)
        - qa: Leaf radiative forcing (W/m2 leaf)

    - __Leaf temperature and energy balance__

        - tleaf: Leaf temperature (K)
        - rnet: Leaf net radiation (W/m2 leaf)
        - lwrad: Longwave radiation emitted from leaf (W/m2 leaf)
        - shflx: Leaf sensible heat flux (W/m2 leaf)
        - lhflx: Leaf latent heat flux (W/m2 leaf)
        - etflx: Leaf transpiration flux (mol H2O/m2 leaf/s)

    - __Boundary layer conductances__

        - gbh: Boundary layer conductance, heat (mol/m2 leaf/s)
        - gbv: Boundary layer conductance, H2O (mol H2O/m2 leaf/s)
        - gbc: Boundary layer conductance, CO2 (mol CO2/m2 leaf/s)

    - __Stomatal conductance__

        - gs: Leaf stomatal conductance (mol H2O/m2 leaf/s)

    - __Photosynthesis__

        - vcmax: Maximum carboxylation rate (umol/m2/s)
        - jmax: Maximum electron transport rate (umol/m2/s)
        - cp: CO2 compensation point (umol/mol)
        - kc: Michaelis-Menten constant for CO2 (umol/mol)
        - ko: Michaelis-Menten constant for O2 (mmol/mol)
        - je: Electron transport rate (umol/m2/s)
        - kp_c4: C4: Initial slope of CO2 response curve (mol/m2/s)
        - ac: Rubisco-limited gross photosynthesis (umol CO2/m2 leaf/s)
        - rd: Leaf respiration rate (umol CO2/m2 leaf/s)
        - aj: RuBP regeneration-limited gross photosynthesis (umol CO2/m2 leaf/s)
        - ap: Product-limited (C3) or CO2-limited (C4) gross photosynthesis
        - ag: Leaf gross photosynthesis (umol CO2/m2 leaf/s)
        - an: Leaf net photosynthesis (umol CO2/m2 leaf/s)
        - cs: Leaf surface CO2 (umol/mol)
        - ci: Leaf intercellular CO2 (umol/mol)
        - hs: Leaf fractional humidity at surface (dimensionless)
        - vpd: Leaf vapor pressure deficit at surface (Pa)

    - __Time step__

        - dt: Model time step (s)
    """

    # Site / canopy -------------------------------------------------------------

    # Leaf height (m)
    height: float = 0.0

    # Canopy leaf area index (m2/m2)
    lai: float = 0.0

    # Hydraulics ----------------------------------------------------------------

    # Aboveground plant stem resistance (MPa.s.m2/mmol H2O)
    rplant: float = 0.0

    # Soil hydraulic resistance (MPa.s.m2/mmol H2O)
    rsoil: float = 0.0

    # Leaf-specific conductance (mmol H2O/m2 leaf/s/MPa)
    lsc: float = 0.0

    # Weighted soil water potential (MPa)
    psi_soil: float = 0.0

    # Leaf water potential (MPa)
    psi_leaf: float = 0.0

    # Fraction of transpiration from each soil layer
    et_loss: list = field(default_factory=list)

    # Radiation -----------------------------------------------------------------

    # Incident solar radiation on leaf [vis, nir]
    swinc: list = field(default_factory=lambda: [0.0, 0.0])

    # Absorbed solar radiation [vis, nir]
    swflx: list = field(default_factory=lambda: [0.0, 0.0])

    # Absorbed PAR (umol photon/m2 leaf/s)
    apar: float = 0.0

    # Leaf radiative forcing (W/m2 leaf)
    qa: float = 0.0

    # Leaf temperature and energy balance ---------------------------------------

    # Leaf temperature (K)
    tleaf: float = 0.0

    # Leaf net radiation (W/m2 leaf)
    rnet: float = 0.0

    # Longwave radiation emitted from leaf (W/m2 leaf)
    lwrad: float = 0.0

    # Leaf sensible heat flux (W/m2 leaf)
    shflx: float = 0.0

    # Leaf latent heat flux (W/m2 leaf)
    lhflx: float = 0.0

    # Leaf transpiration flux (mol H2O/m2 leaf/s)
    etflx: float = 0.0

    # Boundary layer conductances -----------------------------------------------

    # Boundary layer conductance, heat (mol/m2 leaf/s)
    gbh: float = 0.0

    # Boundary layer conductance, H2O (mol H2O/m2 leaf/s)
    gbv: float = 0.0

    # Boundary layer conductance, CO2 (mol CO2/m2 leaf/s)
    gbc: float = 0.0

    # Stomatal conductance ------------------------------------------------------

    # Leaf stomatal conductance (mol H2O/m2 leaf/s)
    gs: float = 0.0

    # Photosynthesis ------------------------------------------------------------

    # Maximum carboxylation rate (umol/m2/s)
    vcmax: float = 0.0

    # Maximum electron transport rate (umol/m2/s)
    jmax: float = 0.0

    # CO2 compensation point (umol/mol)
    cp: float = 0.0

    # Michaelis-Menten constant for CO2 (umol/mol)
    kc: float = 0.0

    # Michaelis-Menten constant for O2 (mmol/mol)
    ko: float = 0.0

    # Electron transport rate (umol/m2/s)
    je: float = 0.0

    # C4: Initial slope of CO2 response curve (mol/m2/s)
    kp_c4: float = 0.0

    # Leaf respiration rate (umol CO2/m2 leaf/s)
    rd: float = 0.0

    # Rubisco-limited gross photosynthesis (umol CO2/m2 leaf/s)
    ac: float = 0.0

    # RuBP regeneration-limited gross photosynthesis (umol CO2/m2 leaf/s)
    aj: float = 0.0

    # Product-limited (C3) or CO2-limited (C4) gross photosynthesis
    ap: float = 0.0

    # Leaf gross photosynthesis (umol CO2/m2 leaf/s)
    ag: float = 0.0

    # Leaf net photosynthesis (umol CO2/m2 leaf/s)
    an: float = 0.0

    # Leaf surface CO2 (umol/mol)
    cs: float = 0.0

    # Leaf intercellular CO2 (umol/mol)
    ci: float = 0.0

    # Leaf fractional humidity at surface (dimensionless)
    hs: float = 0.0

    # Leaf vapor pressure deficit at surface (Pa)
    vpd: float = 0.0

    # Model time step (s)
    dt: float = 0.0

# %% ../nbs/100_parameter_classes.ipynb #33b7287d
@dataclass
class SurEauVegetationParams:
    """Plant parameters — set once at initialisation."""

    # ── General ──────────────────────────────────────────────────────────────
    K: float = 0.5
    transpiration_model: str = "Jarvis"
    transpi_granier_a: float = -0.006
    transpi_granier_b: float = 0.134
    transpi_granier_c: float = 0.0
    gmin20: float = 4.0
    TPhase_gmin: float = 37.5
    Q10_1_gmin: float = 1.2
    Q10_2_gmin: float = 4.8
    canopy_storage_param: float = 1.5
    k_plant_init: float = 0.62

    # Priestley-Taylor equation empirical constant accounting for vapor
    # pressure deficit and resistance values, typically 1.26 for open water or
    # well-watered surfaces
    PT_coeff: float = 1.14
    # ── Leaf ─────────────────────────────────────────────────────────────────
    LAI_max: float = 4.5
    P50_VC_leaf: float = -3.4
    slope_VC_leaf: float = 60.0
    epsilon_sym_leaf: float = 10.0
    pi_full_turgor_leaf: float = -2.1
    apo_frac_leaf: float = 0.4
    sym_frac_leaf: float = 0.4
    LDMC: float = 570.0
    LMA: float = 106.0
    C_LApo_init: float = 1e-5
    # ── Phenology ────────────────────────────────────────────────────────────
    foliage: str = "Evergreen"
    nb_day_LAI: int = 21
    T_base: float = 3.0
    F_crit: float = 450.0
    day_start: int = 55
    day_start_forced: int = 40
    day_end_forced: int = 220
    defoliation: bool = False
    # ── Stem ─────────────────────────────────────────────────────────────────
    P50_VC_stem: float = -3.4
    slope_VC_stem: float = 60.0
    gmin_S: float = 3.0
    pi_full_turgor_stem: float = -2.1
    epsilon_sym_stem: float = 10.0
    vol_stem: float = 40.0
    apo_frac_stem: float = 0.4
    sym_frac_stem: float = 0.2
    C_SApo_init: float = 2e-5
    k_SSym_init: float = 0.26
    f_TRB_to_leaf: float = 0.8
    g_BL_stem: float = 2000.0   # Bark boundary layer conductance (mmol/m²/s)
    # ── Root ─────────────────────────────────────────────────────────────────
    f_root_to_leaf: float = 1.0
    root_radius: float = 0.0002
    root_depth_max: Optional[float] = None
    root_distribution_model: str = "BRP"
    beta_root_profile: float = 0.97
    root_Z50: Optional[float] = None
    root_Z95: Optional[float] = None
    # ── Stomatal regulation ──────────────────────────────────────────────────
    stomatal_reg_formulation: str = "Sigmoid"
    P12_gs: float = -2.07
    P88_gs: float = -2.62
    psi_start_closing: float = -0.5
    psi_close: float = -2.0
    turgor_pressure_at_gs_max: float = 2.0
    # ── Jarvis ───────────────────────────────────────────────────────────────
    g_crown0: float = 45.0
    gs_max: float = 200.0
    gs_night: float = 20.0
    jarvis_PAR: float = 0.006
    T_gs_sens: float = 17.0
    T_gs_optim: float = 25.0
    
    # ── Mortality ────────────────────────────────────────────────────────────
    threshold_mortality: float = 90.0
    # ── Derived (filled by init_par_plant) ────────────────────────────────────
    psi_TLP_leaf: float = 0.0
    psi_TLP_stem: float = 0.0
    P50_gs: float = 0.0
    slope_gs: float = 0.0
    root_distribution: Optional[np.ndarray] = None
    La: Optional[np.ndarray] = None
    Lv: Optional[np.ndarray] = None
    k_SLApo_init: float = 0.0
    k_RSApo_init: Optional[np.ndarray] = None
    k_LSym_init: float = 0.0
    # ── Leaf morphology (new) ────────────────────────────────────────
    leaf_size: float = 50.0        # Characteristic leaf dimension (mm)
    leaf_angle: float = 45.0       # Leaf angle from horizontal (degrees)
    turn_off_EB: bool = False       # Skip energy balance (diagnostic)
    

# %% ../nbs/100_parameter_classes.ipynb #889c6cb7
@dataclass
class SurEauSoilParams:
    """Soil parameters — set once at initialisation."""

    depth: np.ndarray = field(default_factory=lambda: np.array([0.2, 0.8, 2.0]))
    RFC: np.ndarray = field(default_factory=lambda: np.array([75.0, 75.0, 75.0]))
    g_soil0: float = 30.0
    offset_psoil: np.ndarray = field(default_factory=lambda: np.array([0.0, 0.0, 0.0]))
    psoil_at_field_capacity: float = 0.033
    reset_SWC: bool = False
    water_soil_transfer: bool = True
    soil_evap: bool = True
    PTF: str = "VG"
    Ksat: np.ndarray = field(default_factory=lambda: np.array([1.69, 1.69, 1.69]))
    saturation_capacity: np.ndarray = field(
        default_factory=lambda: np.array([0.5, 0.5, 0.5])
    )
    residual_capacity: np.ndarray = field(
        default_factory=lambda: np.array([0.098, 0.098, 0.098])
    )
    alpha_vg: np.ndarray = field(
        default_factory=lambda: np.array([0.0005, 0.0005, 0.0005])
    )
    n_vg: np.ndarray = field(default_factory=lambda: np.array([1.55, 1.55, 1.55]))
    I_vg: np.ndarray = field(default_factory=lambda: np.array([0.5, 0.5, 0.5]))
    b_camp: np.ndarray = field(default_factory=lambda: np.array([4.0, 4.0, 4.0]))
    psie_camp: np.ndarray = field(
        default_factory=lambda: np.array([0.025, 0.025, 0.025])
    )
    # ── Derived ──────────────────────────────────────────────────────────────
    n_layers: int = 0
    layer_thickness: Optional[np.ndarray] = None
    m: Optional[np.ndarray] = None
    V_field_capacity: Optional[np.ndarray] = None
    V_saturation_capacity: Optional[np.ndarray] = None
    V_residual_capacity: Optional[np.ndarray] = None
    V_wilting_point: Optional[np.ndarray] = None
    B_GC: Optional[np.ndarray] = None

# %% ../nbs/100_parameter_classes.ipynb #e38ddf60
@dataclass
class SurEauComputationOptions:
    """Numerical solver options."""

    n_small_timesteps: List[int] = field(default_factory=lambda: [1, 2, 4, 8, 16])
    numerical_scheme: str = "Implicit"
    Lsym: float = 1.0
    Ssym: float = 1.0
    Eord: float = 1.0
    Lcav: int = 1
    Scav: int = 1
    CLapo: float = 1.0
    CTapo: float = 1.0

# %% ../nbs/100_parameter_classes.ipynb #214885cd
@dataclass
class SurEauModelOptions:
    """Simulation configuration."""

    year_start: int = 2000
    year_end: int = 2000
    latitude: float = 43.9
    longitude: float = 43.9
    elevation: float = 0
    output_resolution: str = "subdaily"
    ETP_formulation: str = "PT"
    Rn_formulation: str = "Linacre"
    constant_climate: bool = False
    print_progress: bool = True
    time_steps: np.ndarray = field(default_factory=lambda: np.arange(24))
    comp_options: SurEauComputationOptions = field(
        default_factory=SurEauComputationOptions
    )

# %% ../nbs/100_parameter_classes.ipynb #a855f4d1
@dataclass
class SurEauPlantState:
    """Plant hydraulic state — mutated by the solver, carried forward in time.

    Contains the 4-compartment water potentials (leaf/stem × apoplasm/symplasm),
    cavitation fronts, conductances, capacitances, phenology, and tissue water
    content.  Everything here is needed to restart the simulation from a
    checkpoint.
    """

    # ── Water potentials [MPa] ───────────────────────────────────────────────
    psi_LApo: float = 0.0
    psi_SApo: float = 0.0
    psi_LSym: float = 0.0
    psi_SSym: float = 0.0

    # Cavitation fronts (most-negative ψ ever reached — irreversible)
    psi_LApo_cav: float = 0.0
    psi_SApo_cav: float = 0.0

    # Weighted soil boundary condition passed in from SurEauSoil
    psi_all_soil: float = 0.0

    # ── Hydraulic conductances ───────────────────────────────────────────────
    k_plant: float = 0.0
    k_LSym: float = 0.0
    k_SSym: float = 0.0
    k_RSApo: Optional[np.ndarray] = None  # per soil layer
    k_SLApo: float = 0.0
    k_soil_to_stem: Optional[np.ndarray] = None  # per soil layer

    # ── Capacitances ─────────────────────────────────────────────────────────
    C_LSym: float = 0.0
    C_SSym: float = 0.0
    C_LApo: float = 0.0
    C_SApo: float = 0.0

    # ── Cavitation (percent loss of conductivity) ────────────────────────────
    PLC_leaf: float = 0.0
    PLC_stem: float = 0.0

    # ── LAI & phenology ──────────────────────────────────────────────────────
    LAI_pheno: float = 0.0
    LAI: float = 0.0
    canopy_storage_capacity: float = 0.0
    FCC: float = 0.0
    LAI_dead: float = 0.0

    # ── Phenology accumulator ────────────────────────────────────────────────
    sum_temperature: float = 0.0
    budburst_date: float = np.nan

    # ── Tissue water content (saturated references & current) ────────────────
    #    *_sat_mmol / *_sat_L  : maximum storage at full turgor
    #    *_sat_mmol_per_LA     : same, normalised by leaf area
    #    Q_*_L                 : current water content [L m⁻² ground]

    Q_LApo_sat_mmol: float = 0.0
    Q_LApo_sat_L: float = 0.0
    Q_SApo_sat_mmol: float = 0.0
    Q_SApo_sat_L: float = 0.0
    Q_LSym_sat_mmol: float = 0.0
    Q_LSym_sat_L: float = 0.0
    Q_SSym_sat_mmol: float = 0.0
    Q_SSym_sat_L: float = 0.0
    Q_LApo_sat_mmol_per_LA: float = 0.0
    Q_SApo_sat_mmol_per_LA: float = 0.0
    Q_LSym_sat_mmol_per_LA: float = 0.0
    Q_SSym_sat_mmol_per_LA: float = 0.0
    Q_LApo_L: float = 0.0
    Q_SApo_L: float = 0.0
    Q_LSym_L: float = 0.0
    Q_SSym_L: float = 0.0

    # ── Canopy dry matter [g m⁻² ground] ────────────────────────────────────
    DM_live_canopy: float = 0.0
    DM_dead_canopy: float = 0.0

# %% ../nbs/100_parameter_classes.ipynb #f5200ab0
@dataclass
class SurEauPlantFluxes:
    """Instantaneous fluxes & conductances — computed from state + forcing.

    Everything here can safely be zeroed between timesteps; the solver
    fills them in from SurEauPlantState + atmospheric forcing.
    """

    # ── Stomatal / canopy conductance ────────────────────────────────────────
    gmin: float = 0.0  # cuticular conductance, T-adjusted [mmol m⁻² s⁻¹]
    gmin_S: float = 0.0  # stem cuticular conductance
    regul_fact: float = 0.01  # stomatal regulation factor [0–1]
    gs_bound: float = 0.0  # boundary-layer-limited stomatal cond.
    gs_lim: float = 0.0  # hydraulically limited stomatal cond.
    g_canopy_bound: float = 0.0
    g_canopy_lim: float = 0.0
    g_BL: float = 0.0  # boundary layer conductance
    g_crown: float = 0.0  # crown-level aerodynamic conductance

    # ── Water fluxes [mmol m⁻² s⁻¹ unless _mm suffix] ───────────────────────
    E_prime: float = 0.0  # atmospheric transpiration demand
    E_min: float = 0.0  # minimum (cuticular) leaf transpiration
    E_min_S: float = 0.0  # minimum stem transpiration
    E_bound: float = 0.0  # boundary-layer-limited transpiration
    E_lim: float = 0.0  # hydraulically limited transpiration

    flux_soil_to_stem: Optional[np.ndarray] = None  # per layer
    flux_soil_to_stem_mm: Optional[np.ndarray] = None  # per layer [mm]
    transpiration_mm: float = 0.0
    E_min_mm: float = 0.0
    E_min_S_mm: float = 0.0
    sum_flux_soil_to_stem: float = 0.0

    # ── Interception ─────────────────────────────────────────────────────────
    ppt_soil: float = 0.0  # throughfall reaching soil [mm]
    intercepted_water: float = 0.0  # water held in canopy [mm]
    evaporation_intercepted: float = 0.0  # evaporation of interception [mm]
    ETP_r: float = 0.0  # residual ETP after interception
    ETP: float = 0.0  # potential evapotranspiration

    # ── Leaf energy balance ──────────────────────────────────────────────────
    leaf_temperature: float = np.nan
    leaf_VPD: float = 0.0

# %% ../nbs/100_parameter_classes.ipynb #3bf55fd6
@dataclass
class SurEauPlantDiagnostics:
    """Solver diagnostics and derived fire/moisture outputs.

    Used for logging, quality control, and post-processing — never fed
    back into the hydraulic solver.
    """

    # ── Solver quality ───────────────────────────────────────────────────────
    diag_delta_regul_max: float = 0.0
    diag_delta_PLC_max: float = 0.0
    diag_timestep_hours: float = 0.0
    diag_nwhile_cavit: int = 0

    # ── Fuel moisture content [%] ────────────────────────────────────────────
    DFMC: float = 0.0  # dead fuel moisture content
    LFMC_apo: float = 0.0  # live fuel MC — apoplasm fraction
    LFMC_symp: float = 0.0  # live fuel MC — symplasm fraction
    LFMC: float = 0.0  # live fuel moisture content (total)
    FMC_canopy: float = 0.0  # whole-canopy fuel moisture

# %% ../nbs/100_parameter_classes.ipynb #3b82acd9
@dataclass
class SurEauSoil:
    """Soil state — mutated every timestep."""

    soil_water_stock: Optional[np.ndarray] = None
    psi_soil: Optional[np.ndarray] = None
    k_soil: Optional[np.ndarray] = None
    REW: Optional[np.ndarray] = None
    evaporation: float = 0.0
    drainage: float = 0.0
    ETP: float = 0.0
    RWC: float = 0.0
    REW_tot: float = 0.0
    REW_wp: float = 0.0

# %% ../nbs/100_parameter_classes.ipynb #d13f209a
@dataclass
class SurEauClimate:
    """Daily climate forcing."""

    DOY: int = 0
    year: int = 0
    date: str = ""
    T_air_mean: float = 0.0
    T_air_max: float = 0.0
    T_air_min: float = 0.0
    RH_air_mean: float = 0.0
    RH_air_max: float = 0.0
    RH_air_min: float = 0.0
    PPT: float = 0.0
    RG: float = 0.0
    WS_mean: float = 0.0
    VPD: float = 0.0
    net_radiation: float = 0.0
    ETP: float = 0.0
    T_air_min_prev: float = 0.0
    T_air_max_prev: float = 0.0
    T_air_min_next: float = 0.0

# %% ../nbs/100_parameter_classes.ipynb #3717f324
class SurEauClimateHourly:
    """Sub-daily disaggregated climate."""

    RG: Optional[np.ndarray] = None
    Rn: Optional[np.ndarray] = None
    PAR: Optional[np.ndarray] = None
    potential_PAR: Optional[np.ndarray] = None
    T_air_mean: Optional[np.ndarray] = None
    RH_air_mean: Optional[np.ndarray] = None
    WS: Optional[np.ndarray] = None
    VPD: Optional[np.ndarray] = None
    ETP: Optional[np.ndarray] = None
    PPT: Optional[np.ndarray] = None
    time: Optional[np.ndarray] = None
    n_hours: Optional[np.ndarray] = None
    ETP_veg: Optional[np.ndarray] = None
