# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/111_root_params.ipynb.

# %% auto #0
__all__ = ['root_params']

# %% ../nbs/111_root_params.ipynb #b16c7f88
from .parameter_classes import RootVar

# %% ../nbs/111_root_params.ipynb #bceec9e5
def root_params(rootvar=RootVar) -> RootVar:
    """
    Set fine root parameters.

    __Returns:__

    - RootVar updated object:

        - radius: Fine root radius (m). Default = 0.29e-03

        - density: Fine root density (g biomass / m3 root). Default = 0.31e06

        - resist: Hydraulic resistivity of root tissue (MPa.s.g/mmol H2O). Default 25.0
    """

    # Fine root radius (m)
    rootvar.radius = 0.29e-03

    # Fine root density (g biomass / m3 root)
    rootvar.density = 0.31e06

    # Hydraulic resistivity of root tissue (MPa.s.g/mmol H2O)
    rootvar.resist = 25.0

    return rootvar
