# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/202_sureau_plant_hydraulics.ipynb.

# %% auto #0
__all__ = ['compute_Rs', 'compute_turgor', 'compute_TLP', 'compute_turgor_from_psi', 'compute_PLC', 'compute_PLC_prime',
           'kseries', 'distribute_conductances', 'compute_g_crown', 'compute_root_profile_BRP',
           'compute_root_profile_LDR', 'compute_root_profile', 'compute_root_length', 'compute_regul_fact',
           'calculate_gs_jarvis', 'calculate_Ebound_mm_Granier', 'calculate_Ebound_Granier', 'compute_gmin',
           'compute_E_min', 'compute_T_leaf', 'compute_DFMC']

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #5d006c0a
import numpy as np
from .utils import flux_mm_to_mmol_m2leaf_s
from .parameter_classes import SurEauVegetationParams, SurEauPlantState, SurEauPlantFluxes, SurEauSoilParams

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #658560dd
def compute_Rs(pi_FT, epsilon, psi):
    """
    Compute the relative symplasmic water deficit Rs = 1 − RWC.
 
    Inverts the pressure–volume curve (Ruffault et al. 2022, Eq. 43) to
    obtain the fractional water loss of the symplasm at a given water
    potential ψ. The function handles both regimes of the p–v curve
    (above and below the turgor loss point) 
    
    Above the turgor loss point (Rs1), Rs is found by substituting
    RWC = 1 - Rs into Equation 46 (the product form of Eq. 43),
    yielding a quadratic in Rs:
 
        ε·Rs² + (ψ + π₀ − ε)·Rs − ψ = 0
 
    which is solved with the quadratic formula (minus root).
 
    
    Derivation of the quadratic solved by compute_Rs() 
        
        STEP 1 — Equation 43 (first case): the pressure-volume curve
        ─────────────────────────────────────────────────────────────
            ψ = −π₀ - ε(1 - RWC) + π₀ / RWC
        
                    │
                    │  Multiply both sides by RWC to clear the fraction
                    ▼
        
        STEP 2 — Equation 46: product form
        ───────────────────────────────────
            ψ·RWC + π₀·RWC + ε(1 - RWC)·RWC - π₀ = 0
        
                    │
                    │  Substitute  RWC = 1 - Rs
                    ▼
        
        STEP 3 — After substitution
        ────────────────────────────
            ψ(1 - Rs) + π₀(1 - Rs) + ε·Rs·(1 - Rs) - π₀ = 0
        
                    │
                    │  Expand every product
                    ▼
        
        STEP 4 — Expanded form
        ───────────────────────
            (ψ - ψ·Rs) + (π₀ - π₀·Rs) + (ε·Rs - ε·Rs² - π₀) = 0
        
                    │
                    │  Cancel  +π₀  and  −π₀ , then group by powers of Rs
                    ▼
        
        STEP 5 — Collected by powers of Rs
        ───────────────────────────────────
            -ε·Rs²  +  (−ψ - π₀ + ε)·Rs  +  ψ  =  0
        
                    │
                    │  Multiply everything by -1
                    ▼
        
        STEP 6 — Standard quadratic form  (a·x² + b·x + c = 0)
        ────────────────────────────────────────────────────────
            ε·Rs²  +  (ψ + π₀ - ε)·Rs  -  ψ  =  0
        
            where   a = ε
                    b = (ψ + π₀ - ε)
                    c = −ψ
        
                    │
                    │  Apply quadratic formula, take the MINUS root
                    │  (the plus root gives Rs > 1, physically impossible)
                    ▼
        
        STEP 7 — Quadratic formula (minus root)
        ────────────────────────────────────────
        
                    -b  -  √(b² - 4ac)
            Rs  =  ─────────────────────
                        2a
        
                    -(ψ + π₀ - ε)  -  √( (ψ + π₀ - ε)²  +  4·ε·ψ )
                =   ──────────────────────────────────────────────────────
                                            2·ε
        
            Note: the  +4·ε·ψ  under the square root comes from
                -4ac = -4·ε·(−ψ) = +4·ε·ψ
        
                    │
                    │  Direct translation to Python
                    ▼
        
        STEP 8 — Python implementation
        ──────────────────────────────
        
        Rs1 = (
        -1 * (psi + pi_FT - epsilon)    # ← −b
        - np.sqrt((psi + pi_FT - epsilon) ** 2 + 4 * psi * epsilon) # ← −√(b²−4ac)
        ) / (2 * epsilon)  # ← ÷ 2a
 
 
    Below the turgor loss point (Rs2), turgor is zero and only the
    osmotic term remains (Eq. 43, second case: ψ = π₀/RWC), giving:
 
        Rs = 1 − π₀/ψ
 
    
    Physical analogy: Think of a balloon filled with sugar water.
    Above TLP the balloon is inflated — both the elastic wall (turgor)
    and the sugar concentration (osmotic pressure) resist water loss.
    Below TLP the balloon has deflated — only the sugar concentration
    matters.
 
    __Parameters:__
 
    - pi_FT: Osmotic potential at full turgor π₀ (MPa). Negative value,
        e.g. −2.1. 
 
    - epsilon: Bulk modulus of elasticity ε of the symplasm (MPa).
        Positive value, e.g. 10. 
        
    - psi: Current water potential ψ of the symplasm (MPa). Negative
        value, e.g. −1.5. Corresponds to ``psi_LSym`` or ``psi_SSym``
        
 
    __Returns:__
 
    - Rs: Relative symplasmic water deficit (dimensionless, 0 to 1).
        Rs = 0 means fully hydrated (RWC = 1).
        Rs = 1 means completely desiccated (RWC = 0).
 
   
    Parameters
    ----------
    pi_FT : float
        Osmotic potential at full turgor π₀ (MPa). Negative value,
        
    epsilon : float
        Bulk modulus of elasticity ε of the symplasm (MPa). 
        
    psi : float
        Current water potential ψ of the symplasm (MPa). 
 
    Returns
    -------
    Rs : float
        Relative symplasmic water deficit (dimensionless, 0 to 1).
    """
    
    # Rs1: Above the turgor loss point ------------------------------------------
    # Above turgor loss, both turgor pressure AND osmotic pressure contribute 
    # to ψ.
    Rs1 = (
        
        -1 * (psi + pi_FT - epsilon)
        - np.sqrt((psi + pi_FT - epsilon) ** 2 + 4 * psi * epsilon)
    ) / (2 * epsilon)
    
    # Rs2: Below the turgor loss point ------------------------------------------  
    Rs2 = 1 - pi_FT / psi

    return max(Rs1, Rs2)

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #47aea979
def compute_turgor(pi_FT, epsilon, Rs):
    """
    Compute turgor pressure from the elastic component of the
    pressure–volume curve.
 
    Turgor is the positive internal pressure a plant cell exerts
    against its cell wall when hydrated. It is extracted from
    Equation 43 (first case) of Ruffault et al. (2022) by
    decomposing the water potential into its turgor and osmotic
    components:
 
        ψ  =  P  +  π
 
    where P is turgor pressure and π is osmotic potential. Equation 43
    can be split as:
 
        ψ  =  [ −π₀ − ε(1 − RWC) ]  +  [ π₀ / RWC ]
               ___________________      ___________
                    turgor  P            osmotic  π
 
    Substituting Rs = 1 − RWC into the turgor part gives:
 
        P = −π₀ − ε · Rs
 
    which is what this function computes.
 
    Physical analogy: Think of the cell as a water balloon filled with
    sugar water. The term ``−π₀`` is the "natural inflation" from
    osmosis — even with no external pressure, the sugar solution draws
    water in and inflates the balloon. The term ``−ε·Rs`` is the
    "deflation penalty" — each unit of water lost costs ε MPa of
    turgor. When Rs reaches ``−π₀/ε``, the balloon has fully deflated
    (turgor = 0 = the turgor loss point). Beyond that, the formula
    returns negative values, which are physically impossible, the
    calling code ( `compute_turgor_from_psi` ) clamps the result to
    zero with ``max(0.0, turgor)``.
 
    __Parameters:__
 
    - pi_FT: Osmotic potential at full turgor π₀ (MPa). Negative value,
        e.g. −2.1. Equivalent to ``pi_full_turgor_leaf`` or
        ``pi_full_turgor_stem`` in SurEauVegetationParams.
 
    - epsilon: Bulk modulus of elasticity ε of the symplasm (MPa).
        Positive value, e.g. 10. Controls how fast turgor drops per
        unit of water lost — a stiff cell wall (high ε) loses turgor
        rapidly; a soft wall (low ε) loses turgor gradually. Equivalent
        to ``epsilon_sym_leaf`` or ``epsilon_sym_stem`` in
        SurEauVegetationParams.
 
    - Rs: Relative symplasmic water deficit (dimensionless, 0 to 1).
        Rs = 0 means fully hydrated (RWC = 1); Rs = 1 means completely
        desiccated (RWC = 0). Obtained from `compute_Rs()`.
 
    __Returns:__
 
    - P: Turgor pressure (MPa). Positive when the cell is inflated
        (above turgor loss point), zero or negative when the cell wall
        is flaccid (at or below turgor loss point). The caller should
        clamp to zero if a physically meaningful turgor is needed.

    
    Parameters
    ----------
    pi_FT : float
        Osmotic potential at full turgor π₀ (MPa).  
    epsilon : float
        Bulk modulus of elasticity ε of the symplasm (MPa).  
    Rs : float
        Relative symplasmic water deficit (dimensionless, 0 to 1). 
 
    Returns
    -------
    P : float
        Turgor pressure (MPa). 
    """
    return -pi_FT - epsilon * Rs

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #3865fcac
def compute_TLP(pi_FT, epsilon):
    """Turgor loss point [MPa]."""
    return pi_FT * epsilon / (pi_FT + epsilon)

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #ca000434
def compute_turgor_from_psi(pi_FT, epsilon, psi):
    """Turgor directly from water potential."""
    Rs = compute_Rs(pi_FT, epsilon, psi)
    turgor = compute_turgor(pi_FT, epsilon, Rs)
    return max(0.0, turgor)

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #bb80447f
def compute_PLC(psi, slope, P50):
    """
    Compute the percent loss of hydraulic conductivity from a sigmoidal
    vulnerability curve.
 
    Implements **Equation 15** of Ruffault et al. (2022):
 
 
                          100
        PLC  =  ─────────────────────────────────
                 1 + exp( slope/25 · (ψ − P50) )
 
    The logistic (S-shaped) curve models the progressive failure of
    xylem conduits as water potential becomes more negative. A
    population of vessels has a distribution of breaking points, wide
    conduits cavitate first, narrow ones last, producing a cumulative
    sigmoid failure curve?
 
    Physical analogy: Imagine a bundle of 100 drinking straws of
    varying thickness. As suction increases, the thickest straws
    collapse first. P50 is the suction at which half the straws are
    blocked. ``slope`` controls how uniform the straws are: high slope
    means all similar thickness (sharp transition); low slope means a
    wide range (gradual transition).
 
    The PLC value feeds directly into the conductance reduction of
    Equations 14 and 16:
 
        K_actual = K_max × (100 − PLC) / 100
 
    This creates the positive feedback loop driving hydraulic failure:
    more cavitation → lower conductance → less water supply → more
    negative ψ → more cavitation.
 
    __Parameters:__
 
    - psi: Water potential of the apoplasm ψ (MPa). Negative value,
        e.g. −3.0. Corresponds to ``psi_LApo`` (leaf, Eq. 15) or
        ``psi_SApo`` (stem, Eq. 16) in SurEauPlantState.
 
    - slope: Slope of the linear rate of embolism spread at the
        inflection point P50 (% MPa⁻¹). Positive value, e.g. 60.
        Higher values produce a steeper (more abrupt) transition.
        Equivalent to ``slope_VC_leaf`` or ``slope_VC_stem`` in
        SurEauVegetationParams.
 
    - P50: Water potential causing 50 % loss of hydraulic conductance
        (MPa). Negative value, e.g. −3.4. The single most important
        trait for drought resistance — more negative P50 means more
        resistant. Equivalent to ``P50_VC_leaf`` or ``P50_VC_stem`` in
        SurEauVegetationParams.
 
    __Returns:__
 
    - PLC: Percent loss of conductivity (%, 0 to 100).
        PLC ≈ 0 when ψ >> P50 (safe).
        PLC = 50 when ψ = P50 (by definition).
        PLC ≈ 100 when ψ << P50 (hydraulic failure).
 
    __References:__
 
    - Ruffault et al. (2022), Eq. 15 (leaf) and Eq. 16 (stem, same
      functional form with stem-specific parameters).
    
    __Numerical example (Quercus petraea: P50 = −3.4, slope = 60):__

        ψ = −1.0 MPa  →  PLC =   0.3%   (essentially intact)
        ψ = −2.5 MPa  →  PLC =  10.3%   (early damage)
        ψ = −3.4 MPa  →  PLC =  50.0%   (P50 by definition)
        ψ = −4.3 MPa  →  PLC =  89.7%   (severe damage)
        ψ = −6.0 MPa  →  PLC =  99.8%   (near-total failure)
 
    Parameters
    ----------
    psi : float
        Water potential of the apoplasm ψ (MPa). 
    slope : float
        Slope of the linear rate of embolism spread at the inflection point P50. 
    P50 : float
        Water potential causing 50 % loss of hydraulic conductance (MPa). 
    Returns
    -------
    PLC : float
        Percent loss of conductivity (%, 0 to 100).
    """

    
    return 100.0 / (1.0 + np.exp(slope / 25.0 * (psi - P50)))

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #a857d1e5
def compute_PLC_prime(PLC, slope):
    """
    Compute the derivative of the percent loss of conductivity with
    respect to water potential: dPLC/dψ.
 
    Implements **Equation 26** of Ruffault et al. (2022):
 
                     slope     PLC        PLC
        PLC'  =  − ─────── × ───── × (1 − ─────)
                      25       100        100
 
    This is the derivative of the sigmoidal vulnerability curve
    (Eq. 15) with respect to ψ. It can be verified by differentiating
    the logistic function directly: the derivative of
    ``100 / (1 + exp(−x))`` is ``(100 · exp(−x)) / (1 + exp(−x))²``,
    
    which simplifies to ``(PLC/100) · (1 − PLC/100)`` times the chain
    rule factor ``slope/25``.
 
    The denominator 250,000 in the code is the product of the three
    scaling constants:

        25 × 100 × 100 = 250,000
 
        where:  25   from the slope/25 convention (Pammenter & Vander Willigen 1998)
               100   from PLC/100  (first factor)
               100   from (100 − PLC)/100  (second factor, written as (100 − PLC)/100)
 
        So:  −slope × PLC × (100 − PLC) / 250,000
           = −(slope/25) × (PLC/100) × (1 − PLC/100)
 
    Physical meaning: PLC' tells you how fast pipes are breaking per
    unit drop in water potential. It is steepest at P50 (where
    PLC = 50, so both factors PLC/100 and (1 − PLC/100) equal 0.5)
    and approaches zero at both extremes (PLC ≈ 0 or PLC ≈ 100).
 
    PLC' is used in the solver (`sureau_solver`) to compute the
    **cavitation water-release conductance** K_cav (Equation 25):

        K_cav = −Q_sat_Apo × PLC' / dt
 
    This equivalent conductance lets the water released from bursting
    pipes be treated as a Darcy-type flux, fitting into the same
    numerical framework as all other fluxes in the model.
    
    __References:__
    
    Pammenter, N. W. and Vander Willigen, C.: A mathematical and statistical 
    analysis of the curves illustrating vulnerability of xylem to cavitation, 
    Tree Physiology, 18, 589–593, 1998.
    
    __Parameters:__
 
    - PLC: Current percent loss of conductivity (%, 0 to 100). Obtained
        from `compute_PLC()`. Corresponds to ``PLC_leaf`` or
        ``PLC_stem`` in SurEauPlantState.
 
    - slope: Slope of the linear rate of embolism spread at the
        inflection point P50 (% MPa⁻¹). Positive value, e.g. 60.
        Equivalent to ``slope_VC_leaf`` or ``slope_VC_stem`` in
        SurEauVegetationParams.
 
    __Returns:__
 
    - PLC_prime: Derivative dPLC/dψ (% MPa⁻¹). Always negative or
        zero, because PLC increases (more damage) as ψ decreases
        (more negative water potential).
 
    __Derivation:__
 
        Eq. 15   PLC = 100 / (1 + exp(slope/25 · (ψ − P50)))
              │  differentiate with respect to ψ using the chain rule
              │  d/dψ [100/(1+e^u)] = −100·e^u/(1+e^u)² · du/dψ
              │  where u = slope/25·(ψ−P50), so du/dψ = slope/25
              ▼
              
        Simplify             note that e^u/(1+e^u)² = [1/(1+e^u)]·[e^u/(1+e^u)]
              │                                      = (PLC/100)·(1 − PLC/100)
              ▼
              
        Eq. 26   PLC' = −(slope/25) · (PLC/100) · (1 − PLC/100)
              │  multiply out the denominators: 25 × 100 × 100 = 250,000
              ▼
            
            Code    return −slope × PLC × (100 − PLC) / 250,000
 
    __Numerical example (slope = 60):__
 
        PLC =   0%  →  PLC' = −60 ×   0 × 100 / 250000 =  0.0000  (no pipes breaking)
        PLC =  10%  →  PLC' = −60 ×  10 ×  90 / 250000 = −0.0216  (slow onset)
        PLC =  50%  →  PLC' = −60 ×  50 ×  50 / 250000 = −0.0600  (maximum rate)
        PLC =  90%  →  PLC' = −60 ×  90 ×  10 / 250000 = −0.0216  (slowing down)
        PLC = 100%  →  PLC' = −60 × 100 ×   0 / 250000 =  0.0000  (all pipes gone)
 
    Parameters
    ----------
    PLC : float
        Current percent loss of conductivity (%, 0 to 100). 
    slope : float
        Slope of the linear rate of embolism spread at the inflection point P50  
 
    Returns
    -------
    PLC_prime : float
        Derivative dPLC/dψ (% MPa⁻¹). Always negative or zero.
    """
    return -slope * PLC * (100.0 - PLC) / 250000.0

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #af5c336a
def kseries(k1, k2):
    """Two conductances in series: 1/(1/k1 + 1/k2) = k1*k2/(k1+k2)."""
    return k1 * k2 / (k1 + k2)

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #5af2d22f
def distribute_conductances(
    k_plant_init: float,
    ri: np.ndarray,
    sym_frac_leaf: float = 0.4,
) -> tuple[np.ndarray, float, float]:
    
    """Distribute whole-plant K among root, stem-leaf, and leaf symplasm."""
    frac_RT = 2.0 / 3.0 * (1.0 - sym_frac_leaf)
    frac_TL = 1.0 / 3.0 * (1.0 - sym_frac_leaf)
    k_RSApo_init = ri / frac_RT * k_plant_init
    k_SLApo_init = 1.0 / frac_TL * k_plant_init
    k_LSym_init = 1.0 / sym_frac_leaf * k_plant_init
    return k_RSApo_init, k_SLApo_init, k_LSym_init

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #d7d51ab1
def compute_g_crown(g_crown0: float, wind_speed: float) -> float:
    """Crown aerodynamic conductance."""
    return g_crown0 * max(0.1, wind_speed) ** 0.6

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #7a7162a2
def compute_root_profile_BRP(
    z: np.ndarray,
    beta: float,
) -> np.ndarray:
    """
    Compute per-layer root fractions using the Beta Root Profile model.
 
    Implements **Equation 19** of Ruffault et al. (2022), based on the
    exponential root distribution of Jackson et al. (1996):
 
 
        r_j = β^{z_{j-1} · 100} − β^{z_j · 100}
 
    which is equivalent to differencing the cumulative root fraction:
 
 
        Y(d) = 1 − β^d              (Jackson et al. 1996)
        
        r_j  = Y(z_j) − Y(z_{j-1})
 
    where d is depth in centimeters, β is a species-specific root
    distribution parameter (0 < β < 1), and z_j is the cumulative
    depth of the bottom of layer j in meters (converted to cm
    internally by multiplying by 100).
 
    The parameter β controls how deep roots extend. Think of it as a "root 
    shallowness dial" :
 
    - β close to 0 (e.g. 0.90): roots are very shallow, most mass
      concentrated near the surface.
    
    - β close to 1 (e.g. 0.99): roots are spread deeply into the
      soil, like a deep-rooted tree reaching for groundwater.
 
    The raw fractions from this function may not sum to exactly 1.0
    because the exponential tail extends beyond the deepest layer.
    
    The calling function ``compute_root_profile`` handles
    normalization.
 
    __Parameters:__
 
    - z: Cumulative depth of the bottom of each soil layer (m).
        NumPy array, e.g. ``np.array([0.2, 0.8, 2.0])``. Corresponds
        to ``soil_params.depth`` in SurEauSoilParams.
 
    - beta: Species-specific root distribution parameter
        (dimensionless, 0 < β < 1). Higher values produce deeper root
        profiles. Equivalent to ``beta_root_profile`` in
        SurEauVegetationParams. Reference values from the paper
        (Table 4): *Quercus ilex* β = 0.97, *Fagus sylvatica*
        β = 0.98.
 
    __Returns:__
 
    - rd: Root fraction in each soil layer (dimensionless array).
        Same length as z. Values are non-negative but may not sum to
        exactly 1.0 (see normalization note above).
 
    __References:__
 
    - Ruffault et al. (2022), Eq. 19.
    
    - Jackson, R. B. et al. (1996). A global analysis of root
      distributions for terrestrial biomes. *Oecologia*, 108,
      389–411.
 
    __Derivation:__
 
 
        Jackson et al. 1996    Y(d) = 1 − β^d     (cumulative, d in cm)
              │                evaluate at each layer bottom: 
              │                z in m → z×100 in cm
              ▼
              
        Cumulative array    rd = 1 − β^{z·100}  = [Y(z₁), Y(z₂), ..., Y(zₙ)]
              │             difference consecutive entries (prepend 0 for 
              │             first layer)
              ▼
            Eq. 19          r_j = Y(z_j) − Y(z_{j-1})
              │             direct translation to Python
              ▼
             Code          rd - np.concatenate([[0.0], rd[:-1]])
 
 
    __Numerical example (β = 0.97, depths = [0.2, 0.8, 2.0] m):__
 
    -Cumulative:    Y(20cm)  = 1 − 0.97^20  = 0.4562
                    Y(80cm)  = 1 − 0.97^80  = 0.9124
                    Y(200cm) = 1 − 0.97^200 = 0.9976
 
    -Per-layer:    r₁ = 0.4562 − 0.0    = 0.4562  (45.6% in top 20 cm)
                   r₂ = 0.9124 − 0.4562 = 0.4562  (45.6% in 20–80 cm)
                   r₃ = 0.9976 − 0.9124 = 0.0852  ( 8.5% in 80–200 cm)
                                             ──────
                                     Total = 0.9976  (not exactly 1.0)
 
    Parameters
    ----------
    z : np.ndarray
        Cumulative depth of the bottom of each soil layer (m).  
    beta : float 
         Species-specific root distribution parameter (dimensionless, 0 < β < 1). 
 
    Returns
    -------
    rd : np.ndarray
        Root fraction in each soil layer (dimensionless). Same length as z. 
    """
    rd = 1.0 - beta ** (z * 100)
    return rd - np.concatenate([[0.0], rd[:-1]])

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #e99f8fe4
def compute_root_profile_LDR(
    z: np.ndarray,
    z50: float,
    z95: float,
) -> np.ndarray:
    """
    Compute per-layer root fractions using the Linear Dose-Response
    model.
 
    Implements the logistic root distribution of Schenk & Jackson
    (2002).
 
    The cumulative root fraction at depth d is:
 
                        1
        Y(d) = ────────────────────
                1 + (d / Z50)^{pc}
 
    where:
 
        pc = 2.94 / ln(Z50 / Z95)
 
    The constant 2.94 comes from the logistic curve properties:
    at d = Z50, Y = 0.5 (50% of roots above), and at d = Z95,
    Y ≈ 0.05 (95% of roots above). The shape parameter pc is
    derived so that these two constraints are satisfied
    simultaneously.
 
    Since Z95 > Z50, the ratio Z50/Z95 < 1, so ln(Z50/Z95) < 0,
    and pc is **negative**. This makes (d/Z50)^pc a decreasing
    function of d, so Y(d) **increases** with depth — Y represents
    the cumulative fraction of roots that are ABOVE depth d (or
    equivalently, 1 − Y is the fraction below d). The differencing
    ``yz - concat([0], yz[:-1])`` then yields positive per-layer
    fractions.
 
    Per-layer fractions are obtained by differencing consecutive
    cumulative values, identical to the BRP approach:
 
        r_j = Y(z_j) − Y(z_{j-1})
 
    Physical meaning: Z50 and Z95 are field measurements,
    "half the roots are above this depth" and "almost all roots are
    above this depth." This makes the LDR model convenient when root
    excavation data are reported as depth quantiles rather than as a
    fitted β parameter.
 
    The raw fractions from this function may not sum to exactly 1.0.
    The calling function ``compute_root_profile`` handles
    normalization.
 
    __Parameters:__
 
    - z: Cumulative depth of the bottom of each soil layer (m).
        NumPy array, e.g. ``np.array([0.2, 0.8, 2.0])``. Corresponds
        to ``soil_params.depth`` in SurEauSoilParams.
 
    - z50: Depth above which 50 % of root density is found (m).
        Positive value, e.g. 0.3. Equivalent to ``root_Z50`` in
        SurEauVegetationParams.
 
    - z95: Depth above which 95 % of root density is found (m).
        Positive value, must be greater than z50, e.g. 1.2. Equivalent
        to ``root_Z95`` in SurEauVegetationParams.
 
    __Returns:__
 
    - rd: Root fraction in each soil layer (dimensionless array).
        Same length as z. Values are non-negative but may not sum to
        exactly 1.0 (see normalization note above).
 
    __References:__
 
    - Schenk, H. J. and Jackson, R. B. (2002). The global
      biogeography of roots. *Ecological Monographs*, 72(3), 311–328.
 
    __Derivation:__
 
        Schenk & Jackson 2002   Y(d) = 1 / (1 + (d/Z50)^pc)
              │                 compute shape parameter from Z50, Z95
              │                 pc = 2.94 / ln(Z50 / Z95)
              │                 NOTE: pc is NEGATIVE because Z50 < Z95
              ▼
        Cumulative array        yz = [Y(z₁), Y(z₂), ..., Y(zₙ)]
              │                 yz INCREASES with depth (because pc < 0)
              │                 difference consecutive entries
              │                 (prepend 0 for first layer)
              ▼
        Per-layer               r_j = Y(z_j) − Y(z_{j-1})
 
    __Numerical example (Z50 = 0.3 m, Z95 = 1.2 m,
    depths = [0.2, 0.8, 2.0] m):__
 
        Step 1 — Shape parameter:
            pc = 2.94 / ln(0.3/1.2) = 2.94 / (−1.386) = −2.121
 
        Step 2 — Cumulative fractions (yz INCREASES with depth):
 
            z = 0.2:  (0.2/0.3)^{−2.121} = (0.667)^{−2.121} = 2.404
                      yz = 1/(1 + 2.404) = 0.294
 
            z = 0.8:  (0.8/0.3)^{−2.121} = (2.667)^{−2.121} = 0.128
                      yz = 1/(1 + 0.128) = 0.887
 
            z = 2.0:  (2.0/0.3)^{−2.121} = (6.667)^{−2.121} = 0.018
                      yz = 1/(1 + 0.018) = 0.982
 
        Step 3 — Per-layer fractions (all positive):
 
            r₁ = 0.294 − 0.0   = 0.294  (29.4% in top 20 cm)
            r₂ = 0.887 − 0.294 = 0.593  (59.3% in 20–80 cm)
            r₃ = 0.982 − 0.887 = 0.095  ( 9.5% in 80–200 cm)
                                   ─────
                           Total = 0.982  (not exactly 1.0)
 
        Note: most roots (59.3%) are in the 20–80 cm layer, which
        makes sense for Z50 = 0.3 m — half the roots are above 30 cm,
        so the 0–20 cm layer captures less than half (29.4%), and the
        20–80 cm layer captures the bulk of the remaining roots.
 
    Parameters
    ----------
    z : np.ndarray
        Cumulative depth of the bottom of each soil layer (m).
        
    z50 : float
        Depth above which 50 % of root density is found (m). 
        
    z95 : float
        Depth above which 95 % of root density is found (m). 
 
    Returns
    -------
    rd : np.ndarray
        Root fraction in each soil layer (dimensionless). Same length as z. 
    """
    pc = 2.94 / np.log(z50 / z95)
    yz = 1.0 / (1.0 + (z / z50) ** pc)
    
    return yz - np.concatenate([[0.0], yz[:-1]])

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #0243ccf9
def compute_root_profile(
    soil_params: SurEauSoilParams,
    veg_params: SurEauVegetationParams,
) -> np.ndarray:
    """
    Compute and normalize the vertical root distribution across soil
    layers.
 
    Dispatches to either the Beta Root Profile model
    (`compute_root_profile_BRP`, implementing Equation 19 of
    Ruffault et al. 2022) or the Linear Dose-Response model
    (`compute_root_profile_LDR`, Schenk & Jackson 2002), depending
    on `veg_params.root_distribution_model`. 
    Then normalizes the resulting fractions so they sum to exactly 1.0 within 
    the maximum rooting depth.
 
    The normalization is necessary because:
 
    1. The exponential (BRP) or logistic (LDR) tail extends
       mathematically beyond the deepest soil layer, leaving a small
       fraction unaccounted for (e.g. 0.24% for β = 0.97 at 2.0 m
       depth).
    2. The user may specify a ``root_depth_max`` shallower than the
       deepest soil layer, requiring roots below that depth to be
       zeroed and redistributed.
 
    The normalization strategy is: (a) find all layers within
    ``root_depth_max``, (b) assign any "missing" root fraction
    (1.0 − sum) to the deepest valid layer, and (c) zero out all
    layers below ``root_depth_max``.
 
    Physical analogy: Think of the root system as a bundle of straws
    spread vertically through the soil. Each soil layer gets a certain
    number of straws. β (or Z50/Z95) controls how the bundle tapers
    with depth. The normalization step says: "All straws must be
    accounted for within the rooting depth. If some mathematically
    fell below the deepest layer, assign them to that deepest layer
    instead."
 
    The output feeds directly into:
 
    - `compute_root_length` → Eqs. 17–18: per-layer root area
      RAI_j = RAI × r_j and root length density Lv.
    - `distribute_conductances` → Eq. 17: per-layer root-to-stem
      conductance K_{Rj} = RAI_j × K_{R-SApo}.
    - The Gardner-Cowan soil-to-root geometry factor B_GC
      (`compute_soil_root_geometry`), which depends on La and Lv
      derived from the root distribution.
 
    __Parameters:__
 
    - soil_params: SurEauSoilParams object with the following
        attributes:
 
        - depth: Cumulative depth of the bottom of each soil layer
            (m). NumPy array, e.g. ``np.array([0.2, 0.8, 2.0])``.
 
    - veg_params: SurEauVegetationParams object with the following
        attributes:
 
        - root_distribution_model: Which model to use. ``"BRP"``
            (default) for Beta Root Profile (Eq. 19), or ``"LDR"``
            for Linear Dose-Response (Schenk & Jackson 2002).
        - beta_root_profile: β parameter for BRP (dimensionless,
            0 < β < 1). Only used when model is ``"BRP"``.
        - root_Z50: Depth above which 50 % of roots are found (m).
            Only used when model is ``"LDR"``.
        - root_Z95: Depth above which 95 % of roots are found (m).
            Only used when model is ``"LDR"``.
        - root_depth_max: Maximum rooting depth (m). If None, defaults
            to the depth of the deepest soil layer. Roots below this
            depth are zeroed and their fraction is reassigned to the
            deepest valid layer.
 
    __Returns:__
 
    - rd: Normalized root fraction in each soil layer (dimensionless
        NumPy array). Same length as ``soil_params.depth``. Guaranteed
        to sum to exactly 1.0. Layers below ``root_depth_max`` have
        rd = 0.
 
    __References:__
 
    - Ruffault et al. (2022), Eq. 19 (BRP model).
    - Jackson, R. B. et al. (1996). A global analysis of root
      distributions for terrestrial biomes. *Oecologia*, 108,
      389–411.
    - Schenk, H. J. and Jackson, R. B. (2002). The global
      biogeography of roots. *Ecological Monographs*, 72(3), 311–328.
 
    __Normalization logic:__
 
 
        1. Compute raw fractions via BRP (Eq. 19) or LDR
        raw fractions may sum to < 1.0 (exponential tail)
              │         
              ▼
        2. Find layers within root_depth_max
        idx = layers where z ≤ zmax
              │  
              ▼
        3. Compute missing fraction 
        deficit = 1.0 − sum(rd[idx])
              │  
              ▼
        4. Assign deficit to deepest valid layer
        rd[last_valid] += deficit
              │  
              ▼
        5. Zero out layers below root_depth_max 
        rd[below_zmax] = 0.0
              │  
              ▼
        6. Return rd (sums to exactly 1.0)
 
    __Numerical example (BRP, β = 0.97, depths = [0.2, 0.8, 2.0] m,
    root_depth_max = 2.0 m):__
 
 
        Raw BRP output:    [0.4562, 0.4562, 0.0852]   sum = 0.9976
        Deficit:           1.0 − 0.9976 = 0.0024
        Add to last layer: [0.4562, 0.4562, 0.0876]   sum = 1.0000 
 
    __Numerical example (BRP, β = 0.97, depths = [0.2, 0.8, 2.0] m,
    root_depth_max = 0.8 m):__
 
 
        Raw BRP output:    [0.4562, 0.4562, 0.0852]
        Valid layers:      idx = [0, 1] (z ≤ 0.8)
        Deficit:           1.0 − (0.4562 + 0.4562) = 0.0876
        Add to last valid: [0.4562, 0.5438, 0.0000]  sum = 1.0000 ✓
        Layer 3 zeroed:    roots below 0.8 m reassigned to layer 2
 
    Parameters
    ----------
    soil_params : SurEauSoilParams
        Soil parameters object with the following attributes:
               # - depth : np.ndarray
               #   Cumulative depth of the bottom of each soil layer (m).
    veg_params : SurEauVegetationParams
        Vegetation parameters object with the following attributes:
                # - root_distribution_model : str
                #   "BRP" for Beta Root Profile (Eq. 19) or "LDR"
                # - beta_root_profile : float
                #   β parameter for BRP (dimensionless, 0 < β < 1). Only used when model is "BRP".
                # - root_Z50 : float or None
                #   Depth above which 50 % of roots are found (m). Only used when model is "LDR".
                # - root_Z95 : float or None
                #   Depth above which 95 % of roots are found (m). Only used when model is "LDR".
                # - root_depth_max : float or None
                #   Maximum rooting depth (m). If None, defaults to the depth of the deepest soil layer.
 
    Returns
    -------
    rd : np.ndarray
        Normalized root fraction in each soil layer (dimensionless).
    """
    z = soil_params.depth
   
   # Select model ---------------------------------------------------------------
    if veg_params.root_distribution_model == "LDR":
        rd = compute_root_profile_LDR(z, veg_params.root_Z50, veg_params.root_Z95)
    else:
        rd = compute_root_profile_BRP(z, veg_params.beta_root_profile)
    
    # Normalise so roots sum to 1 within root_depth_max -------------------------
    zmax = veg_params.root_depth_max if veg_params.root_depth_max is not None else z[-1]
    
    idx = np.where(z <= zmax)[0]
    
    if len(idx) > 0:
        last = idx[-1]
        rd[last] += 1.0 - np.sum(rd[idx])
        mask = np.ones(len(z), dtype=bool)
        mask[idx] = False
        rd[mask] = 0.0
    
    return rd

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #72d59c8a
def compute_root_length(
    soil_params: SurEauSoilParams,
    veg_params: SurEauVegetationParams,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Compute root length per soil area (La) and root length density per
    soil volume (Lv) for each soil layer.
 
    Implements **Equation 18** of Ruffault et al. (2022) plus two
    geometric conversions described in the text surrounding Eq. 21:
 
    1. Distribute total root area index (RAI) across layers using the
       root fractions r_j from `compute_root_profile` (**Eq. 18**):

           RAI_j = RAI × r_j
 
    2. Convert root surface area to root length using cylinder
       geometry (A = 2πrL, so L = A / 2πr):
 
           La_j = RAI_j / (2π r)
 
    3. Convert root length per soil area to root length per soil
       volume by dividing by the effective layer thickness (corrected
       for rock fragments, same correction as **Eq. 23**): 
 
           Lv_j = La_j / [ thickness_j × (1 − RFC_j/100) ]
 
    Both outputs feed into **Equation 21**,  the soil-to-root
    conductance via `compute_soil_root_geometry`, which computes
    the Gardner-Cowan geometry factor B_GC:
 
        b    = 1 / √(π Lv_j)           (mean half-distance between roots)
        B_GC = 2π La_j / ln(b / r)     (geometry factor in Eq. 21)
    
    La_j represents the total length of roots, obtained by dividing surface 
    area by the circumference of one straw (2πr).
    
    Lv_j represents how densely packed the roots are per unit room volume, 
    accounting for rocks taking upspace. From Lv, you can calculate how far 
    apart the straws are on average (1/√(πLv)), which determines how far water 
    must travel through the soil to reach the nearest straw.
 
    __Parameters:__
 
    - soil_params: SurEauSoilParams object with the following
        attributes:
 
        - layer_thickness: Thickness of each soil layer (m). NumPy
            array, e.g. ``np.array([0.2, 0.6, 1.2])``. Computed by
            `sureau_soil_params()` from ``soil_params.depth``.
 
        - RFC: Rock fragment content of each soil layer (%). NumPy
            array, e.g. ``np.array([75.0, 75.0, 75.0])``. Reduces
            the effective soil volume available for roots.
 
    - veg_params: SurEauVegetationParams object with the following
        attributes:
 
        - LAI_max: Maximum leaf area index of the stand
            (m²_leaf / m²_soil). E.g. 4.5.
 
        - f_root_to_leaf: Root-to-leaf area ratio RaLa
            (dimensionless). E.g. 1.0 means root surface area equals
            leaf area. Equivalent to ``RaLa`` in Eq. 18 text.
 
        - root_distribution: Normalized root fraction in each soil
            layer (dimensionless array summing to 1.0). Output of
            `compute_root_profile()`. Equivalent to r_j in Eq. 18.
 
        - root_radius: Fine root radius r (m). E.g. 0.0002 (= 0.2
            mm). Equivalent to ``dR`` in Table 1.
 
    __Returns:__
 
    - La: Root length per unit soil area for each layer
        (m_root / m²_soil). NumPy array, same length as
        ``soil_params.depth``. Stored as ``veg_params.La``.
 
    - Lv: Root length density per unit soil volume for each layer
        (m_root / m³_soil). NumPy array, same length as
        ``soil_params.depth``. Stored as ``veg_params.Lv``.
 
    __References:__
 
    - Ruffault et al. (2022), Eq. 18 (per-layer RAI), Eq. 21 (where
      La and Lv are used), Eq. 23 (same rock fragment correction).
    - Jackson, R. B. et al. (1996) for the root distribution r_j.
 
    __Derivation:__
 
         Eq. 18 RAI = LAI × RaLa        (total root area index)
              │                     distribute across layers using r_j 
              │                                 (Eq. 18)
              ▼
            Eq. 18               RAI_j = RAI × r_j    (per-layer root area)
              │                   cylinder geometry: A = 2πrL → L = A/(2πr)
              ▼
              La        La_j = RAI_j / (2π r)   (length per soil area)
              │         divide by effective layer volume
              │         V_eff = thickness × (1 − RFC/100)   (same as Eq. 23)
              ▼
              Lv         Lv_j = La_j / V_eff     (density per soil volume)
              │          feeds into Eq. 21 via compute_soil_root_geometry
              ▼
           Eq. 21               b = 1/√(πLv)       (half-distance between roots)
                             B_GC = 2πLa / ln(b/r)   (Gardner-Cowan factor)
 
    __Numerical example (LAI_max = 4.5, f_root_to_leaf = 1.0,
    root_radius = 0.0002 m, root_distribution = [0.4562, 0.4562,
    0.0876], layer_thickness = [0.2, 0.6, 1.2] m, RFC = [75, 75,
    75] %):__
 
        Step 1 — Total RAI:
            RAI = 4.5 × 1.0 = 4.5 m²_root / m²_soil
 
        Step 2 — Per-layer RAI (Eq. 18):
            RAI₁ = 4.5 × 0.4562 = 2.053 m²/m²
            RAI₂ = 4.5 × 0.4562 = 2.053 m²/m²
            RAI₃ = 4.5 × 0.0876 = 0.394 m²/m²
 
        Step 3 — Root length per soil area (La):
            La₁ = 2.053 / (2π × 0.0002) = 2053 / 0.001257 = 1634 m/m²
            La₂ = 2.053 / 0.001257                         = 1634 m/m²
            La₃ = 0.394 / 0.001257                         =  313 m/m²
 
        Step 4 — Root length density per soil volume (Lv):
            V_eff₁ = 0.2 × (1 − 0.75) = 0.05 m
            Lv₁ = 1634 / 0.05 = 32,680 m/m³   (32.7 km of root per m³)
 
            V_eff₂ = 0.6 × 0.25 = 0.15 m
            Lv₂ = 1634 / 0.15 = 10,893 m/m³   (10.9 km per m³)
 
            V_eff₃ = 1.2 × 0.25 = 0.30 m
            Lv₃ = 313 / 0.30  =  1,043 m/m³   ( 1.0 km per m³)
 
        These feed into compute_soil_root_geometry:
            b₁ = 1/√(π × 32680) = 0.0031 m  (3.1 mm between roots)
            b₂ = 1/√(π × 10893) = 0.0054 m  (5.4 mm between roots)
            b₃ = 1/√(π ×  1043) = 0.0175 m  (17.5 mm between roots)
 
    Parameters
    ----------
    soil_params : SurEauSoilParams
        Soil parameters object with the following attributes:
        # - layer_thickness : np.ndarray
        #    Thickness of each soil layer (m).    
        # - RFC : np.ndarray
        #    Rock fragment content of each soil layer (%). 
    veg_params : SurEauVegetationParams
        Vegetation parameters object with the following attributes:
        # - LAI_max : float
        #    Maximum leaf area index of the stand (m²_leaf / m²_soil).
        # - f_root_to_leaf : float
        #    Root-to-leaf area ratio RaLa (dimensionless). 
        # - root_distribution : np.ndarray
        #    Normalized root fraction in each soil layer (dimensionless, sums to 1.0). 
        # - root_radius : float
        #    Fine root radius r (m). E.g. 0.0002.
 
    Returns
    -------
    La : np.ndarray
        Root length per unit soil area for each layer
    Lv : np.ndarray
        Root length density per unit soil volume for each layer
        
    """
    # Compute root area index ---------------------------------------------------
    RAI = veg_params.LAI_max * veg_params.f_root_to_leaf
    
    # Compute root length per soil area -----------------------------------------
    La = RAI * veg_params.root_distribution /(2 * np.pi * veg_params.root_radius)
    
    # Compute roots density per unit room volume --------------------------------
    Lv = La / (soil_params.layer_thickness * (1.0 - soil_params.RFC / 100.0))
    
    return La, Lv

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #4e87f8df
def compute_regul_fact(psi, params: SurEauVegetationParams):
    """
    Compute the stomatal regulation factor γ and its derivative dγ/dψ.
 
    The regulation factor γ is a dimensionless number between 0 and 1
    that controls how open the stomata are, linking water potential to
    stomatal conductance via **Equation 33** of Ruffault et al. (2022):
 
        g_stom = γ × g_stom,max
 
    where g_stom,max is the maximum stomatal conductance (set by light,
    temperature, CO₂). When γ = 1, stomata are fully open; when γ = 0,
    stomata are fully closed.
 
    The derivative dγ/dψ is needed by the implicit solver for the
    transpiration linearization in **Equation 60**, which accounts for
    the quick adjustment of stomatal regulation to water potential
    changes within a single timestep.
 
    Three formulations are available, selected by
    ``params.stomatal_reg_formulation``:
 
    **Sigmoid** (default, used in the paper)
        Implements **Equation 34**: γ follows a sigmoid (S-curve) that
        transitions smoothly from 1 (open) to 0 (closed) as ψ_LSym
        decreases. The shape is controlled by P50_gs (ψ at 50%
        closure) and slope_gs (steepness of the transition). This is
        the same logistic functional form as the xylem vulnerability
        curve (Eq. 15), but applied to stomata using leaf symplasm ψ
        rather than apoplasm ψ, and scaled to 0–1 instead of 0–100.
 
    **PiecewiseLinear** (not in the paper)
        A simple three-zone model: fully open above ψ_start_closing,
        linearly decreasing between ψ_start_closing and ψ_close,
        fully closed below ψ_close.
 
    **Turgor** (not in the paper)
        A mechanistic model that ties stomatal opening directly to
        guard cell turgor pressure, computed from the pressure–volume
        curve (Eqs. 43/46 via __compute_Rs()__ and __compute_turgor()__ ).
        Stomata open proportionally to turgor / turgor_at_gs_max.
 
    Physical analogy: Think of γ as a valve controlled by water
    pressure. When the pipe pressure (ψ) is high (less negative), the
    valve is wide open. As pressure drops, the valve progressively
    shuts. The Sigmoid formulation describes a valve that shuts
    rapidly over a narrow pressure range (like a snap-action valve).
    The PiecewiseLinear formulation describes a valve that shuts at a
    constant rate. The Turgor formulation describes a valve directly
    driven by the inflation of the guard cells.
 
    __Parameters:__
 
    - psi: Water potential of the leaf symplasm ψ_LSym (MPa). Negative
        value, e.g. −2.0. Corresponds to ``psi_LSym`` in
        SurEauPlantState.
 
    - params: SurEauVegetationParams object with the following
        attributes (which are read depends on the formulation):
 
        - stomatal_reg_formulation: Which model to use. ``"Sigmoid"``
            (default, Eq. 34), ``"PiecewiseLinear"``, or ``"Turgor"``.
 
        - Sigmoid parameters:
 
            - P50_gs: Water potential at 50 % stomatal closure (MPa).
                Derived from (P12_gs + P88_gs) / 2 in
                `sureau_vegetation_params` .
                
            - slope_gs: Slope of the stomatal sigmoid at P50_gs
                (% MPa⁻¹). Derived from 100 / (P12_gs − P88_gs) in
                `sureau_vegetation_params` .
 
        - PiecewiseLinear parameters:
 
            - psi_start_closing: ψ above which stomata are fully open
                (MPa). E.g. −0.5.
            - psi_close: ψ below which stomata are fully closed (MPa).
                E.g. −2.0.
 
        - Turgor parameters:
 
            - pi_full_turgor_leaf: Osmotic potential at full turgor π₀
                (MPa). E.g. −2.1.
            - epsilon_sym_leaf: Bulk elastic modulus ε (MPa). E.g. 10.
            - turgor_pressure_at_gs_max: Turgor at which stomata are
                fully open (MPa). E.g. 2.0.
 
    __Returns:__
 
    - rf: Stomatal regulation factor γ (dimensionless, 0 to 1).
        γ = 1 means stomata fully open (no water stress).
        γ = 0 means stomata fully closed (maximum water stress).
 
    - rfp: Derivative dγ/dψ (MPa⁻¹). Always non-negative (γ increases
        as ψ increases). Used in the implicit solver for the
        transpiration linearization (Eq. 60). Returns 0.0 for the
        Turgor formulation (no analytical derivative provided).
 
    __References:__
 
    - Ruffault et al. (2022), Eq. 33 (stomatal conductance), Eq. 34
      (sigmoid regulation factor), Eq. 60 (transpiration
      linearization using dγ/dψ).
      
    -  Pammenter, N. W. and Vander Willigen, C.: A mathematical and statistical 
    analysis of the curves illustrating vulnerability of xylem to cavitation, 
    Tree Physiology, 18, 589–593, 1998.
 
    __Derivation of the Sigmoid formulation (Eq. 34):__

 
            Eq. 34      γ = 1 − 1 / (1 + exp(α(ψ − P50_gs)))
              │         define PL_gs = 1/(1+exp(α(ψ−P50)))  where α = slope_gs/25
              ▼
         Code line 1   PL_gs = 1/(1 + exp(α(ψ − P50_gs)))
              │             flip: γ = 1 − PL_gs
              ▼
        Code line 2           rf = 1 − PL_gs
 
    __Derivation of the Sigmoid derivative:__
 
 
          Start from            γ = 1 − PL_gs
              │             dγ/dψ = −d(PL_gs)/dψ
              │             d(PL_gs)/dψ = −α × PL_gs × (1−PL_gs)
              │             and (1−PL_gs) = γ = rf
              ▼
            Result                dγ/dψ = α × PL_gs × rf
              │                direct translation to Python
              ▼
            Code               al = slope_gs / 25.0
                              rfp = al * PL_gs * rf
 
    __Numerical example, Sigmoid (Quercus petraea: P12_gs = −2.07,
    P88_gs = −2.62, giving P50_gs = −2.345, slope_gs = 182):__
  
        ψ = −1.5 MPa (mild stress):
            α = 182/25 = 7.28
            PL_gs = 1/(1+exp(7.28×0.845)) = 0.002
            γ = 0.998          ← stomata 99.8% open
            dγ/dψ = 0.015
 
        ψ = −2.345 MPa (at P50_gs):
            PL_gs = 0.5
            γ = 0.500          ← stomata half closed
            dγ/dψ = 1.82      ← maximum sensitivity
 
        ψ = −2.8 MPa (severe stress):
            PL_gs = 0.965
            γ = 0.035          ← stomata 96.5% closed
            dγ/dψ = 0.246
 
    __PiecewiseLinear formulation:__
 
        Zone 1 (ψ > ψ_start):    γ = 1.0,  dγ/dψ = 0
              │     ψ decreasing
              ▼
        Zone 2 (ψ_close < ψ < ψ_start):
                                  γ = (ψ − ψ_close) / (ψ_start − ψ_close)
                                  dγ/dψ = 1 / (ψ_start − ψ_close)
              │  ψ decreasing
              ▼
        Zone 3 (ψ < ψ_close):    γ = 0.0,  dγ/dψ = 0
 
    __Numerical example, PiecewiseLinear (ψ_start = −0.5, ψ_close = −2.0):__
  
        ψ = −0.2 MPa  →  γ = 1.000,  dγ/dψ = 0.000  (Zone 1: fully open)
        ψ = −0.5 MPa  →  γ = 1.000,  dγ/dψ = 0.000  (boundary)
        ψ = −1.0 MPa  →  γ = 0.667,  dγ/dψ = 0.667  (Zone 2: linear ramp)
        ψ = −1.5 MPa  →  γ = 0.333,  dγ/dψ = 0.667  (Zone 2: linear ramp)
        ψ = −2.0 MPa  →  γ = 0.000,  dγ/dψ = 0.000  (boundary)
        ψ = −2.5 MPa  →  γ = 0.000,  dγ/dψ = 0.000  (Zone 3: fully closed)
 
    __Turgor formulation:__
  
        Eq. 43 (via compute_Rs)      Rs = f(ψ, π₀, ε)
              │
              ▼
        Turgor (via compute_turgor)   P = −π₀ − ε·Rs
              │
              ▼
        Regulation factor             γ = clamp(P / P_at_gs_max, 0, 1)
                                      dγ/dψ = 0   (no analytical derivative)
 
    __Numerical example, Turgor (π₀ = −2.1, ε = 10,
    turgor_at_gs_max = 2.0):__
  
        ψ = −0.5 MPa  →  Rs = 0.026, P = 1.84  →  γ = 0.920  (mostly open)
        ψ = −1.5 MPa  →  Rs = 0.121, P = 0.89  →  γ = 0.445  (half closed)
        ψ = −2.3 MPa  →  Rs = 0.193, P = 0.17  →  γ = 0.085  (nearly closed)
        ψ = −2.7 MPa  →  Rs = 0.210, P = 0.00  →  γ = 0.000  (turgor loss)
 
    Parameters
    ----------
    psi : float
        Water potential of the leaf symplasm ψ_LSym (MPa). 
    params : SurEauVegetationParams
        Vegetation parameters object. Which attributes are read depends on the formulation:
        # - stomatal_reg_formulation : str
        #    ``"Sigmoid"`` (default), ``"PiecewiseLinear"``, or ``"Turgor"``.
        # Sigmoid:
        # - P50_gs : float
        #    Water potential at 50 % stomatal closure (MPa). Derived
        #    from ``(P12_gs + P88_gs) / 2``.
        # - slope_gs : float
        #    Slope of the stomatal sigmoid at P50_gs (% MPa⁻¹).
        #    Derived from ``100 / (P12_gs − P88_gs)``.
        # PiecewiseLinear:
        # - psi_start_closing : float
        #    ψ above which stomata are fully open (MPa).
        # - psi_close : float
        #    ψ below which stomata are fully closed (MPa).
        # Turgor:
        # - pi_full_turgor_leaf : float
        #    Osmotic potential at full turgor π₀ (MPa).
        # - epsilon_sym_leaf : float
        #    Bulk elastic modulus ε (MPa).
        # - turgor_pressure_at_gs_max : float
        #    Turgor at which stomata are fully open (MPa).
 
    Returns
    -------
    rf : float
        Stomatal regulation factor γ (dimensionless, 0 to 1).
    rfp : float
        Derivative dγ/dψ (MPa⁻¹). Always non-negative. Returns 0.0 for the Turgor formulation.
    """
    
    # Get stomatal formultaion --------------------------------------------------
    form = params.stomatal_reg_formulation

    # Formulation 1 -------------------------------------------------------------
    if form == "PiecewiseLinear":
        
        # If soil is wet enough that the plant has no reason to restrict 
        # water loss.
        if psi > params.psi_start_closing:
            
            return 1.0, 0.0
        
        # Linear closure
        # Between `psi_start_closing` and `psi_close`, γ drops linearly from 1 
        # to 0. The formula is simple linear interpolation
        elif psi > params.psi_close:
            
            # γ = (ψ − ψ_close) / (ψ_start − ψ_close)
            rf = (psi - params.psi_close) / (
                params.psi_start_closing - params.psi_close
            )
            
            # The derivative is a constant
            rfp = 1.0 / (params.psi_start_closing - params.psi_close)
            
            return rf, rfp
        else:
            
            # Full closure
            return 0.0, 0.0
    # Formulation 2 -------------------------------------------------------------
    elif form == "Sigmoid":
        
        # Percent loss of stomatal conductance" using a sigmoid with 
        # stomata-specific parameters.
        
        # Uses the leaf symplasm water potential ψ_LSym 
        PL_gs = 1.0 / (1.0 + np.exp(params.slope_gs / 25.0 * (psi - params.P50_gs)))
        
        # Equation 34
        rf = 1.0 - PL_gs
        
        # Computing the derivative dγ/dψ
        # The derivative of γ with respect to ψ is needed by the implicit 
        # solver for Equation 60 — the transpiration linearization that 
        # accounts for the quick adjustment of stomatal regulation to water 
        # potential changes during a timestep.
        al = params.slope_gs / 25.0
        rfp = al * PL_gs * rf
        
        return rf, rfp
    
    # Formulation 3 -------------------------------------------------------------
    elif form == "Turgor":
        
        # Compute the water deficit Rs from ψ using the pressure-volume curve 
        # inversion (the function we documented earlier — Eq. 43/46).
        Rs = compute_Rs(params.pi_full_turgor_leaf, params.epsilon_sym_leaf, psi)
        
        # Compute turgor P = −π₀ − ε·Rs (the function we documented earlier, 
        # turgor component of Eq. 43).
        turgor = compute_turgor(params.pi_full_turgor_leaf, params.epsilon_sym_leaf, Rs)
        
        # Normalize turgor to a 0–1 scale
        rf = max(0.0, min(1.0, turgor / params.turgor_pressure_at_gs_max))
        
        # The derivative is returned as 0.0.
        # The turgor formulation doesn't provide an analytical derivative to 
        # the solver. This means the implicit scheme's transpiration 
        # linearization (Eq. 60) won't account for stomatal adjustment within a 
        # timestep when using this formulation, which may require smaller 
        return rf, 0.0

    return 1.0, 0.0

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #2a0d9e8c
def calculate_gs_jarvis(
    fluxes: SurEauPlantFluxes,
    params: SurEauVegetationParams,
    PAR: float,
) -> SurEauPlantFluxes:
    """Jarvis-type stomatal conductance with temperature correction."""
    
    T = fluxes.leaf_temperature
    
    gs_max_T = max(
        0.0, params.gs_max / (1 + ((T - params.T_gs_optim) / params.T_gs_sens) ** 2)
    )
    gs_night_T = max(
        0.0, params.gs_night / (1 + ((T - params.T_gs_optim) / params.T_gs_sens) ** 2)
    )
    
    fluxes.gs_bound = gs_night_T + (gs_max_T - gs_night_T) * (
        1 - np.exp(-params.jarvis_PAR * PAR)
    )
    
    return fluxes

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #80aa8908
def calculate_Ebound_mm_Granier(ETP, LAI, a=-0.006, b=0.134, c=0.0):
    """Granier-type energy-limited transpiration [mm]."""
    return max(0.0, ETP * (a * LAI**2 + b * LAI + c))

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #fe66fac4
def calculate_Ebound_Granier(
    ETP: float,
    LAI: float,
    time_step: float,
    params: SurEauVegetationParams,
) -> float:
    """Ebound in mmol/m²leaf/s from Granier formulation."""

    ebound_mm = calculate_Ebound_mm_Granier(
        ETP,
        LAI,
        params.transpi_granier_a,
        params.transpi_granier_b,
        params.transpi_granier_c,
    )
    return flux_mm_to_mmol_m2leaf_s(ebound_mm, time_step, LAI)

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #b365b92d
def compute_gmin(
    fluxes: SurEauPlantFluxes,
    veg_params: SurEauVegetationParams,
) -> float:
    """gmin as function of leaf temperature (Cochard et al. 2019)."""
    
    # Extract params from classes -----------------------------------------------
    
    # Extract from fluxes 
    leaf_temp = fluxes.leaf_temperature

    # Extract from vegetation params 
    gmin20 = veg_params.gmin20
    TPhase = veg_params.TPhase_gmin
    Q10_1 = veg_params.Q10_1_gmin
    Q10_2 = veg_params.Q10_2_gmin

    # Eqs. 31–32 ----------------------------------------------------------------
    if leaf_temp <= TPhase:
        return gmin20 * Q10_1 ** ((leaf_temp - 20) / 10)
    else:
        return (
            gmin20
            * Q10_1 ** ((TPhase - 20) / 10)
            * Q10_2 ** ((leaf_temp - TPhase) / 10)
        )

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #d9efb937
def compute_E_min(
    gmin: float,
    g_BL: float,
    g_crown: float,
    VPD: float,
    P_atm: float = 101.3,
) -> float:
    """Minimal transpiration from cuticular/boundary layer/crown conductances."""
    return VPD / P_atm / (1.0 / gmin + 1.0 / g_BL + 1.0 / g_crown)


# %% ../nbs/202_sureau_plant_hydraulics.ipynb #46b5f5b4
def compute_T_leaf(
    state: SurEauPlantState,
    fluxes: SurEauPlantFluxes,
    veg_params: SurEauVegetationParams,
    clim: dict,
) -> tuple[float, float, float]:
    
    """
    Compute leaf temperature, boundary-layer conductance, and leaf VPD
    by solving a linearized leaf energy balance.
 
    Implements the leaf energy balance described in SurEau C version (Cochard et
    al. 2021):
  
    The approach is a **linearized single-step Penman-Monteith
    solution**: the leaf temperature is found analytically as a
    departure from air temperature, rather than iteratively (as in
    the Newton-Raphson approach of ``leaf_temperature.py`` in the
    Bonan framework). Both solve the same physical problem, finding
    the temperature at which energy in (absorbed radiation) equals
    energy out (longwave emission + sensible heat + latent heat).
 
    The core equation for the leaf-to-air temperature difference is:
 
                 γ* × Rni × r_blr / (ρ·cp)  −  VPD
        δT  =  ──────────────────────────────────────
                            Δ  +  γ*
 
    where:
 
    - Rni is the isothermal net radiation (W/m²), the radiation the
      leaf would absorb if it were at air temperature.
    - r_blr is the combined boundary-layer + radiative resistance
      (s/m), representing the non-evaporative heat loss pathway.
    - γ* = γ × (r_st / r_blr) is the modified psychrometric constant,
      weighting the stomatal resistance against the convective +
      radiative resistance. When stomata are open (r_st small), γ* is
      small and transpirational cooling dominates (δT < 0). When
      stomata are closed (r_st huge), γ* is large and the leaf heats
      up (δT > 0).
    - Δ is the slope of the saturation vapor pressure curve (kPa/°C).
    - VPD is the air vapor pressure deficit (kPa).
 
    The function also computes the **leaf VPD**, the actual driving
    force for transpiration, which accounts for both the elevated
    leaf temperature (raising e_sat) and the reduced water activity
    at low water potentials (the Kelvin equation correction).This
    correction is critical for accurately computing residual
    transpiration under extreme drought.
 
    Physical analogy: The leaf is a wet surface sitting in a breeze.
    Radiation heats it up; transpiration cools it down. The energy
    balance finds the temperature at which these effects balance.
    A leaf with open stomata (low r_st) is like a wet towel in the
    wind — much cooler than the air. A leaf with closed stomata
    (high r_st) is like a dry rock — warmer than the air because it
    can only cool by convection and longwave emission.
 
    __Parameters:__
 
    - T_air: Air temperature (°C). 
 
    - PAR: Photosynthetically active radiation (µmol/m²/s). E.g. 500.
        Used to estimate shortwave radiation via ``SWR = PAR × 0.5495``
        and cloud cover via ``PAR / potential_PAR``.
 
    - potential_PAR_val: Clear-sky potential PAR (µmol/m²/s). Used to
        estimate cloud cover for atmospheric longwave radiation. If 0
        (nighttime), cloud cover is set to 0.
 
    - WS: Wind speed (m/s). Floored at 0.1 m/s internally. Faster
        wind thins the boundary layer, increasing convective cooling.
 
    - RH: Relative humidity (%). E.g. 65. Used to compute actual vapor
        pressure and VPD.
 
    - gs: Stomatal conductance (mmol/m²/s). Only used when
        ``transpiration_model="Jarvis"``. Default None (treated as 0).
        Combined with g_cuti in parallel to give the total leaf
        conductance to water vapor, as in Eq. 29.
 
    - g_cuti: Cuticular conductance (mmol/m²/s). Only used when
        ``transpiration_model="Jarvis"``. Default None (treated as 0).
        The residual conductance when stomata are fully closed.
 
    - E_inst: Instantaneous transpiration rate (mmol/m²/s). Only used
        when ``transpiration_model="Granier"``. Default None. The
        effective conductance is back-calculated as g = E / (VPD/P_atm).
 
    - psi_leaf: Leaf water potential (MPa). Default 0.0. Used in the
        Kelvin equation correction for vapor pressure inside the leaf.
        Only significant under severe drought (ψ < −5 MPa).
 
    - leaf_size: Characteristic leaf dimension (mm). Default 50.
        Leaves > 3 mm use the flat-plate boundary layer formula;
        smaller leaves (needles) use the cylinder formula. Larger
        leaves have thicker boundary layers.
 
    - leaf_angle: Leaf angle from horizontal (degrees). Default 45.
        Affects how much direct shortwave radiation the leaf
        intercepts: ``SWRabs = a_SWR × cos(angle) × SWR``.
 
    - turn_off_EB: If True, skip the energy balance and return T_air
        as the leaf temperature. Default False. Diagnostic option for
        testing without energy balance feedback.
 
    - transpiration_model: ``"Jarvis"`` (default) computes stomatal
        resistance from gs + g_cuti conductances. ``"Granier"``
        back-calculates effective conductance from E_inst.
 
    __Returns:__
 
    - T_leaf: Leaf temperature (°C). 
 
    - g_bl: Boundary layer conductance (mmol/m²/s). Used downstream
        in the conductance chain for computing E_min (Eqs. 29–30) and
        canopy-level conductances. Stored as ``fluxes.g_BL``.
 
    - VPD_leaf: Vapor pressure deficit at the leaf surface (kPa).
        Accounts for leaf temperature (via e_sat at T_leaf) and water
        activity correction (via Kelvin equation at ψ_leaf). Drives
        all transpiration calculations downstream.
 
    __References:__
 
    - Cochard, H. et al. (2021) — CPRM21 — SurEau: a mechanistic
      model of plant water relations under extreme drought. *Ann.
      For. Sci.*, 78, 1–23. (Energy balance formulation.)
      
    - Jones, H. G. (2013). *Plants and microclimate*. Cambridge
      University Press. (Boundary layer conductance, Eqs. 29–30 text.)
      
    - Brutsaert, W. (1975). On a derivable formula for longwave
      radiation from clear skies. *Water Resources Research*, 11(5),
      742–744. (Atmospheric emissivity.)
      
    - Buck, A. L. (1981). New equations for computing vapor pressure
      and enhancement factor. *J. Appl. Meteorol.*, 20, 1527–1532.
      (Saturation vapor pressure.)
 
    __Computation stages:__
 
        Stage 1 — Atmospheric properties
        ─────────────────────────────────
        Tetens equation       e_sat = a·exp(b·T/(T+z))        (kPa)
        Actual VP             ea = e_sat × RH/100              (kPa)
        Slope                 Δ = e_sat·b·z / (T+z)²          (kPa/°C)
        Cloud cover           cc = PAR / potential_PAR          (0–1)
                              NOTE:cc=1 means CLEAR sky, cc=0 means overcast,
                              opposite to meteorological convention.
        Atm. emissivity       ε_air = f(ea, T, cc)             (Brutsaert 1975)
        VPD                   VPDx = e_sat − ea                (kPa)
 
        Stage 2 — Radiation balance
        ───────────────────────────
        Absorbed SW           SWRabs = 0.5 × cos(angle) × SWR  (W/m²)
        Incoming LW           LWRin = ε_air × σ × T⁴           (W/m²)
        Outgoing LW           LWRout = ε_leaf × σ × T⁴         (W/m², at T_air)
        Isothermal net rad    Rni = SWRabs + LWRin − LWRout     (W/m²)
        Radiative resistance  r_r = ρ·cp / (4·ε·σ·T³)          (s/m)
 
        Stage 3 — Boundary layer
        ────────────────────────
        BL resistance         r_bl = f(WS, leaf_size)           (Jones 2013)
        BL conductance        g_bl = (1/r_bl) × 1000 × 40      (mmol/m²/s)
        Combined non-evap     r_blr = r_bl ∥ r_r                (parallel)
 
        Stage 4 — Stomatal resistance
        ─────────────────────────────
        Jarvis:  r_st = 1/(gs + g_cuti) × 1000 × 40            (s/m)
        Granier: r_st = 1/(E/VPD × P_atm) × 1000 × 40         (s/m)
 
        Stage 5 — Penman-Monteith temperature solution
        ───────────────────────────────────────────────
        Modified γ            γ* = γ × (r_st / r_blr)
        Leaf−air ΔT           δT = (γ*·Rni·r_blr/(ρ·cp) − VPD) / (Δ + γ*)
        Leaf temperature      T_leaf = T_air + δT               (°C)
 
        Stage 6 — Leaf VPD with Kelvin correction
        ──────────────────────────────────────────
        e_sat at T_air        Buck (1981) equation               (Pa)
        e_air                 e_sat_air × RH/100                 (Pa)
        e_sat at T_leaf       Buck (1981) at T_leaf              (Pa)
        Kelvin correction     e_leaf = e_sat_leaf × exp(ψ·Vw/(R·T))  (Pa)
        Leaf VPD              VPD_leaf = (e_leaf − e_air) / 1000 (kPa)
 
    __Kelvin equation detail:__
 
    The vapor pressure inside the leaf is not simply e_sat(T_leaf)
    because dissolved solutes and the negative water potential reduce
    the water activity. The correction is:
 
        e_leaf = e_sat(T_leaf) × exp(ψ × Vw / (R × T))
 
    where Vw = 18.02 × 10⁻⁶ m³/mol (molar volume of water), R = 8.314
    J/mol/K, T in Kelvin, and ψ in MPa. The pre-computed constant
    2.16947115 ≈ Vw × 10⁶ / R handles the MPa-to-Pa conversion.
 
    At ψ = −2 MPa, T = 25°C: correction = exp(−2 × 2.169/298) = 0.986
    (1.4% reduction — small).
 
    At ψ = −10 MPa, T = 25°C: correction = exp(−10 × 2.169/298) = 0.930
    (7% reduction — significant for residual transpiration under extreme
    drought).
 
    __Numerical example (T_air = 25°C, PAR = 500, WS = 2 m/s,
    RH = 50%, gs = 100 mmol/m²/s, g_cuti = 4 mmol/m²/s):__
 
        Stage 1: e_sat = 3.17 kPa, ea = 1.58 kPa, VPD = 1.59 kPa
                 Δ = 0.189 kPa/°C
 
        Stage 2: SWR ≈ 275 W/m², SWRabs ≈ 97 W/m²
                 LWRin ≈ 370 W/m², LWRout ≈ 382 W/m²
                 Rni ≈ 85 W/m²
 
        Stage 3: r_bl ≈ 90 s/m, r_r ≈ 220 s/m
                 r_blr ≈ 64 s/m (parallel)
 
        Stage 4: r_st = 40000 / 104 ≈ 385 s/m
                 (gs+g_cuti = 104 mmol/m²/s → 0.0026 m/s → r = 385 s/m)
 
        Stage 5: γ* = 0.066 × (385/64) = 0.397
                 δT = (0.397×85×64/1306 − 1.59) / (0.189+0.397)
                    = (1.66 − 1.59) / 0.586
                    = 0.12°C
                 T_leaf = 25.12°C (barely above air — transpiration
                 cools effectively when stomata are open)
 
        With stomata closed (gs = 0, g_cuti = 4 only):
                 r_st ≈ 10,000 s/m
                 γ* = 0.066 × (10000/64) = 10.3
                 δT = (10.3×85×64/1306 − 1.59) / (0.189+10.3)
                    = (42.9 − 1.59) / 10.49
                    = 3.94°C
                 T_leaf = 28.94°C (nearly 4°C above air —
                 much less evaporative cooling)
 
    Parameters
    ----------
    T_air : float
        Air temperature (°C).
    PAR : float
        Photosynthetically active radiation (µmol/m²/s).
    potential_PAR_val : float
        Clear-sky potential PAR (µmol/m²/s). Used to estimate cloud cover.
    WS : float
        Wind speed (m/s). Floored at 0.1 m/s internally.
    RH : float
        Relative humidity (%).
    gs : float or None
        Stomatal conductance (mmol/m²/s). Only used when `transpiration_model="Jarvis"`. Default None.
    g_cuti : float or None
        Cuticular conductance (mmol/m²/s). Only used when `transpiration_model="Jarvis"`. Default None.
    E_inst : float or None
        Instantaneous transpiration rate (mmol/m²/s). Only used when `transpiration_model="Granier"`. Default None.
    psi_leaf : float
        Leaf water potential (MPa). Default 0.0. Used in the Kelvin equation correction for vapor pressure inside the leaf.
    leaf_size : float
        Characteristic leaf dimension (mm). Default 50. Leaves > 3 mm use the flat-plate boundary layer formula; smaller leaves use the cylinder formula.
    leaf_angle : float
        Leaf angle from horizontal (degrees). Default 45. Affects interception of direct shortwave radiation.
    turn_off_EB : bool
        If True, skip the energy balance and return T_air as the leaf temperature. Default False.
    transpiration_model : str
        ``"Jarvis"`` (default) or ``"Granier"``. Controls how stomatal resistance is computed.
 
    Returns
    -------
    T_leaf : float
        Leaf temperature (°C).
        
    g_bl : float
        Boundary layer conductance (mmol/m²/s).
        
    VPD_leaf : float
        Vapor pressure deficit at the leaf surface (kPa), corrected
        for leaf temperature and water activity.
    """
    # Extract data --------------------------------------------------------------
    
    # Extract from climate dict 
    T_air = clim["T_air_mean"]
    PAR = clim["PAR"]
    potential_PAR_val = clim["potential_PAR"]
    WS = max(clim["WS"], 0.1)
    RH = clim["RH_air_mean"]
    
    # Extract from plant fluxes 
    gs = fluxes.gs_lim
    g_cuti = fluxes.gmin
    
    # Extract from plant state 
    psi_leaf = state.psi_LSym
    
    # Extract from vegetation params 
    leaf_size = veg_params.leaf_size
    leaf_angle = veg_params.leaf_angle
    transpiration_model = veg_params.transpiration_model
    turn_off_EB = veg_params.turn_off_EB
    

    # Constants and unit conversions --------------------------------------------
        
    # Convert PAR (photosynthetically active radiation, µmol/m²/s) back to 
    # shortwave radiation in W/m²
    SWR = PAR * 0.5495
    a_SWR = 0.5
    
    # Leaf emissivity for longwave radiation
    em_leaf = 0.97
    
    # Stefan-Boltzmann constant  
    SB = 5.6704e-8
    
    # Air density ρ (kg/m³) and specific heat of air at constant pressure 
    # c_p (J/kg/K).
    rho = 1.292
    Cp = 1010
    
    # Psychrometric constant γ (kPa/°C).
    gamma_psy = 0.066
    
    # Coefficients of the Tetens equation for saturation vapor pressure:
    a_coef, b_coef, z_coef = 0.61121, 17.502, 240.97

    # Cloud cover and atmospheric properties
    cloud_cover = min(PAR / potential_PAR_val, 1.0) if potential_PAR_val > 0 else 0.0

    # Saturation vapor pressure at air temperature (kPa), using the Tetens 
    # equation.
    esat = a_coef * np.exp(b_coef * T_air / (T_air + z_coef))
    
    # Actual vapor pressure (kPa) from relative humidity.
    ea = esat * RH / 100
    
    # Slope of the saturation vapor pressure curve
    # This slope is critical in the Penman-Monteith framework, it determines how 
    # much of the available energy goes into evaporation versus heating
    s = esat * b_coef * z_coef / (T_air + z_coef) ** 2
    
    # Atmospheric emissivity ε_air for incoming longwave radiation. This uses the 
    # Brutsaert (1975) clear-sky emissivity formula modified for cloud cover:
    em_air = (1 - 0.84 * cloud_cover) * 1.31 * (
        (10 * ea / (T_air + 273.15)) ** (1 / 7)
    ) + 0.84 * cloud_cover
    
    # Vapor pressure deficit of the air (kPa). This drives transpiration, 
    # the drier the air, the larger VPDx, the more water the leaf loses.
    VPDx = esat - ea

    # Radiation balance
    SWRabs = a_SWR * np.cos(np.radians(leaf_angle)) * SWR
    
    # Incoming longwave radiation from the atmosphere (W/m²).
    LWRin = em_air * SB * (T_air + 273.15) ** 4
    
    # Outgoing longwave radiation from the leaf (W/m²). 
    # This uses T_air, not T_leaf. 
    LWRout = em_leaf * SB * (T_air + 273.15) ** 4
    
    # Isothermal net radiation. Net radiation the leaf would receive if it 
    # were at air temperature.
    Rni = SWRabs + LWRin - LWRout
    
    # Radiative resistance r_r (s/m)
    # r_r tells you how much the "radiative cooling pathway" resists heat 
    # removal. A cold leaf (low T) has high r_r (longwave cooling is weak); 
    # a hot leaf (high T) has low r_r (longwave cooling is strong).
    rr = rho * Cp / (4 * em_leaf * SB * (T_air + 273.15) ** 3)

    # Boundary layer resistance
    gflat, jflat = 0.00662, 0.5
    gcyl, jcyl = 0.00403, 0.6
    
    # Boundary layer resistance r_bl (s/m). 
    # Leaves larger than 3 mm use the flat-plate formula; smaller ones (needles)
    # use the cylinder formula. The factor 1.5 accounts for both sides of the 
    # leaf. The leaf_size / 1000 converts from mm to m
    
    # Larger leaves have thicker boundary layers (higher resistance) because 
    # the still-air layer has more distance to grow. 
    # Faster wind thins the boundary layer (lower resistance). 
    # The exponents (0.5 and 0.6) come from laminar boundary layer theory.
    
    if leaf_size > 3:
        rbl = 1 / (1.5 * gflat * (WS**jflat / (leaf_size / 1000) ** (1 - jflat)))
    else:
        rbl = 1 / (1.5 * gcyl * (WS**jcyl / (leaf_size / 1000) ** (1 - jcyl)))

    # Convert boundary layer resistance (s/m) to boundary layer conductance in 
    # SurEau units (mmol/m²/s). 
    g_bl = 1 / rbl * 1000 * 40
    
    # Combined boundary layer + radiative resistance in parallel
    rblr = 1 / (1 / rbl + 1 / rr)
    
    # Stomatal Resistance -------------------------------------------------------
    
    # Jarvis
    if transpiration_model == "Jarvis":
        gs_val = gs if gs is not None else 0.0
        g_cuti_val = g_cuti if g_cuti is not None else 0.0
        if gs_val + g_cuti_val > 0:
            rst = 1.0 / (gs_val + g_cuti_val) * 1000 * 40
        else:
            rst = 9999.99
    
    # Granier
    else: 
        
        # Effective conductance is back-calculated from the instantaneous 
        # transpiration rate: g = E / (VPD/P_atm), then converted to resistance. 
        #E_val = E_inst if E_inst is not None else 0.0
        E_val = fluxes.E_lim + fluxes.E_min
        g = E_val / max(VPDx, 1e-10) * 101.3
        rst = 1.0 / max(g, 1e-10) * 1000 * 40 if g > 0 else 9999.99

    # Penman-Monteith temperature solution --------------------------------------
    # Weights the "aerodynamic" contribution against the "radiative" 
    # contribution. When stomata are wide open (rst small), γ* is small and 
    # transpirational cooling dominates. 
    # When stomata are closed (rst huge), γ* is large and the leaf heats up.
    ym = gamma_psy * (rst / rblr)
    
    # Leaf-to-air temperature difference ----------------------------------------
    # Linearized Penman-Monteith solution for leaf temperature:
    
    #               γ* × Rni × r_blr / (ρ·cp)  −  VPD
    # delta_T  =  ──────────────────────────────────────
    #                         Δ  +  γ*
    
    # The term γ* × Rni × r_blr / (ρ·cp) represents the heating effect of 
    # absorbed radiation. 
    # More radiation + higher stomatal resistance (closed stomata) = more heating.

    # The term −VPD represents the cooling effect of transpiration. 
    # Drier air (higher VPD) = more cooling.
    
    # The term Δ + γ* represents the combined sensitivity of the system. 
    # Δ (slope of saturation curve) controls how much a temperature 
    # rise increases evaporative demand.
    
    # When stomata are open: γ* is small, VPD dominates the numerator, 
    # δT is negative (leaf cooler than air).

    # When stomata are closed: γ* is huge, the Rni term dominates, 
    # δT is positive (leaf warmer than air).
    delta_T = (ym * Rni * rblr / (rho * Cp) - VPDx) / (s + ym)
    
    # leaf temperature in °C 
    T_leaf = T_air + delta_T

    # Leaf VPD calculation ------------------------------------------------------
    
    # Saturation vapor pressure at air temperature and actual vapor pressure in 
    # Pa
    e_sat_air = 611.21 * np.exp((18.678 - T_air / 234.5) * T_air / (257.14 + T_air))
    e_air = e_sat_air * RH / 100
    
    # Saturation vapor pressure at the leaf temperature (Pa)
    #Since T_leaf ≠ T_air, the air inside the leaf (which is assumed to be 
    # saturated) has a different vapor pressure than saturated air at 
    # ambient temperature.
    e_sat_leaf = 611.21 * np.exp((18.678 - T_leaf / 234.5) * T_leaf / (257.14 + T_leaf))
    
    # Kelvin correction
    # e_leaf = e_sat(T_leaf) × exp(ψ × V_w / (R × T)) corrects the 
    # saturated vapor pressure inside the leaf for the effect of water 
    # potential using the Kelvin equation (also called the thermodynamic 
    # water activity correction)
    
    # where:  
    #    - ψ is the leaf water potential (MPa)
    #    - V_w is the molar volume of water (1.8 × 10⁻⁵ m³/mol)
    #    - R is the gas constant (8.314 J/mol/K)
    #    - T is temperature in Kelvin
    
    # This matters for accurately computing residual transpiration under extreme 
    # drought
    e_leaf = e_sat_leaf * np.exp(psi_leaf * 2.16947115 / (T_leaf + 273.15))
    
    # Leaf-to-air vapor pressure deficit (kPa). This is the actual driving force 
    # for transpiration, accounting for both the elevated leaf temperature 
    # (which raises e_sat) and the reduced water activity
    VPD_leaf = max(0.0, (e_leaf - e_air) / 1000)
    
    # Skip the energy balance? --------------------------------------------------
    if turn_off_EB:
        return T_air, g_bl, VPD_leaf
    return T_leaf, g_bl, VPD_leaf

# %% ../nbs/202_sureau_plant_hydraulics.ipynb #b4db467e
def compute_DFMC(VPD, FM0=5.43, FM1=52.91, m=0.64):
    """Dead fuel moisture content [%dry mass] (De Dios et al. 2015)."""
    return FM0 + FM1 * np.exp(-m * VPD)
