# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/201_sureau_vegetation_params.ipynb.

# %% auto #0
__all__ = ['sureau_vegetation_params']

# %% ../nbs/201_sureau_vegetation_params.ipynb #f3a5c494
from plant_hydraulics.sureau_plant_hydraulics import (
    compute_TLP,
    compute_root_profile,
    compute_root_length,
    distribute_conductances,
)

from .parameter_classes import SurEauSoilParams, SurEauVegetationParams

# %% ../nbs/201_sureau_vegetation_params.ipynb #b16c7f88
def sureau_vegetation_params(
    veg: SurEauVegetationParams,
    soil: SurEauSoilParams,
) -> SurEauVegetationParams:
    """
    Compute derived vegetation parameters from raw SurEau plant parameters.

    Calculates turgor loss points for leaf and stem, stomatal regulation
    sigmoid parameters, root distribution and root length density across
    soil layers, and partitions whole-plant hydraulic conductance among
    root-to-stem, stem-to-leaf, and leaf symplasm pathways.

    __Parameters:__

    - veg: SurEauVegetationParams object with the following input attributes:

        - Pressure-volume curve:
            - pi_full_turgor_leaf: Osmotic potential at full turgor, leaf (MPa).
            - epsilon_sym_leaf: Bulk elastic modulus, leaf symplasm (MPa).
            - pi_full_turgor_stem: Osmotic potential at full turgor, stem (MPa).
            - epsilon_sym_stem: Bulk elastic modulus, stem symplasm (MPa).

        - Stomatal regulation:
            - stomatal_reg_formulation: Regulation model: "Sigmoid", "PiecewiseLinear", or "Turgor".
            - P12_gs: Water potential at 12% stomatal closure (MPa).
            - P88_gs: Water potential at 88% stomatal closure (MPa).

        - Root distribution:
            - root_depth_max: Maximum rooting depth (m). If None, uses deepest soil layer.
            - root_distribution_model: Root profile model: "BRP" (beta) or "LDR" (linear dose-response).
            - beta_root_profile: Beta parameter for BRP root distribution (-).
            - root_Z50: Depth at 50% root density for LDR model (m).
            - root_Z95: Depth at 95% root density for LDR model (m).
            - LAI_max: Maximum leaf area index (m2/m2).
            - f_root_to_leaf: Root area index to LAI ratio (-).
            - root_radius: Fine root radius (m).

        - Hydraulic conductance:
            - k_plant_init: Initial whole-plant hydraulic conductance (mmol/m2leaf/s/MPa).
            - sym_frac_leaf: Fraction of whole-plant resistance in leaf symplasm (-).

    - soil: SurEauSoilParams object with the following required attributes:

        - depth: Cumulative depth of each soil layer bottom (m).
        - layer_thickness: Thickness of each soil layer (m).
        - RFC: Rock fragment content for each layer (%).

    __Returns:__

    - veg: Updated SurEauVegetationParams object with the following derived attributes:

        - psi_TLP_leaf: Turgor loss point, leaf (MPa).
        - psi_TLP_stem: Turgor loss point, stem (MPa).
        - P50_gs: Water potential at 50% stomatal closure (MPa).
        - slope_gs: Slope of the stomatal sigmoid curve (1/MPa).
        - root_distribution: Normalised root fraction in each soil layer (-).
        - La: Root area index per soil layer (m2root/m2soil).
        - Lv: Root length density per soil layer (m root/m3 soil).
        - k_RSApo_init: Initial root-to-stem apoplasm conductance per layer (mmol/m2leaf/s/MPa).
        - k_SLApo_init: Initial stem-to-leaf apoplasm conductance (mmol/m2leaf/s/MPa).
        - k_LSym_init: Initial leaf symplasm conductance (mmol/m2leaf/s/MPa).

    Parameters
    ----------
    veg : SurEauVegetationParams
        SurEau vegetation parameters object with the following input attributes:

        Pressure-volume curve:
        - pi_full_turgor_leaf : float
            Osmotic potential at full turgor, leaf (MPa).
        - epsilon_sym_leaf : float
            Bulk elastic modulus, leaf symplasm (MPa).
        - pi_full_turgor_stem : float
            Osmotic potential at full turgor, stem (MPa).
        - epsilon_sym_stem : float
            Bulk elastic modulus, stem symplasm (MPa).

        Stomatal regulation:
        - stomatal_reg_formulation : str
            Regulation model: "Sigmoid", "PiecewiseLinear", or "Turgor".
        - P12_gs : float
            Water potential at 12% stomatal closure (MPa).
        - P88_gs : float
            Water potential at 88% stomatal closure (MPa).

        Root distribution:
        - root_depth_max : float or None
            Maximum rooting depth (m). If None, uses deepest soil layer.
        - root_distribution_model : str
            Root profile model: "BRP" (beta) or "LDR" (linear dose-response).
        - beta_root_profile : float
            Beta parameter for BRP root distribution (-).
        - root_Z50 : float or None
            Depth at 50% root density for LDR model (m).
        - root_Z95 : float or None
            Depth at 95% root density for LDR model (m).
        - LAI_max : float
            Maximum leaf area index (m2/m2).
        - f_root_to_leaf : float
            Root area index to LAI ratio (-).
        - root_radius : float
            Fine root radius (m).

        Hydraulic conductance:
        - k_plant_init : float
            Initial whole-plant hydraulic conductance (mmol/m2leaf/s/MPa).
        - sym_frac_leaf : float
            Fraction of whole-plant resistance in leaf symplasm (-).

    soil : SurEauSoilParams
        SurEau soil parameters object with the following required attributes:
        - depth : np.ndarray
            Cumulative depth of each soil layer bottom (m).
        - layer_thickness : np.ndarray
            Thickness of each soil layer (m).
        - RFC : np.ndarray
            Rock fragment content for each layer (%).

    Returns
    -------
    veg : SurEauVegetationParams
        Updated SurEau vegetation parameters object with the following derived attributes:
        - psi_TLP_leaf : float
            Turgor loss point, leaf (MPa).
        - psi_TLP_stem : float
            Turgor loss point, stem (MPa).
        - P50_gs : float
            Water potential at 50% stomatal closure (MPa).
        - slope_gs : float
            Slope of the stomatal sigmoid curve (1/MPa).
        - root_distribution : np.ndarray
            Normalised root fraction in each soil layer (-).
        - La : np.ndarray
            Root area index per soil layer (m2root/m2soil).
        - Lv : np.ndarray
            Root length density per soil layer (m root/m3 soil).
        - k_RSApo_init : np.ndarray
            Initial root-to-stem apoplasm conductance per layer (mmol/m2leaf/s/MPa).
        - k_SLApo_init : float
            Initial stem-to-leaf apoplasm conductance (mmol/m2leaf/s/MPa).
        - k_LSym_init : float
            Initial leaf symplasm conductance (mmol/m2leaf/s/MPa).
    """

    # Turgor loss points
    veg.psi_TLP_leaf = compute_TLP(veg.pi_full_turgor_leaf, veg.epsilon_sym_leaf)
    veg.psi_TLP_stem = compute_TLP(veg.pi_full_turgor_stem, veg.epsilon_sym_stem)

    # Sigmoid stomatal regulation parameters
    if veg.stomatal_reg_formulation == "Sigmoid":
        veg.P50_gs = (veg.P12_gs + veg.P88_gs) / 2
        veg.slope_gs = 100 / (veg.P12_gs - veg.P88_gs)

    # Root distribution
    if veg.root_depth_max is None:
        veg.root_depth_max = soil.depth[-1]
    veg.root_distribution = compute_root_profile(soil, veg)
    veg.La, veg.Lv = compute_root_length(soil, veg)

    # Distribute conductances
    k_RSApo, k_SLApo, k_LSym = distribute_conductances(
        veg.k_plant_init, veg.root_distribution, veg.sym_frac_leaf
    )
    veg.k_RSApo_init = k_RSApo
    veg.k_SLApo_init = k_SLApo
    veg.k_LSym_init = k_LSym

    return veg
