# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/203_sureau_soil_hydraulics.ipynb.

# %% auto #0
__all__ = ['compute_soil_VG', 'compute_soil_Campbell', 'compute_soil_conductance_and_psi', 'compute_infiltration',
           'update_soil_water', 'set_SWC_to_field_capacity', 'compute_evaporation']

# %% ../nbs/203_sureau_soil_hydraulics.ipynb #5d006c0a
import numpy as np
import pandas as pd
from .utils import compute_VPD, flux_leaf_to_stand
from .parameter_classes import SurEauSoil, SurEauSoilParams

# %% ../nbs/203_sureau_soil_hydraulics.ipynb #856e4dfc
def compute_soil_VG(soil: SurEauSoil, params: SurEauSoilParams) -> SurEauSoil:
    """Transform soil moisture to water potential and conductance using Van Genuchten
    
    Imagine each soil layer is a sponge sitting in a bucket.

    REW (Relative Extractables Water) tells you what fraction of the sponge's
    usable capacity is still filled.

    REW = 1 means soaking wet 
    
    REW = 0 means only residual water trapped in the tiniest pores remains.

    k_soil (hydraulic conductance) tells you how fast water can flow through
    that sponge. A wet sponge lets water through easily; a nearly dry one barely
    lets anything pass.

    psi_soil (water potential) tells you how hard the sponge is holding its
    remaining water. A wet sponge barely holds on (ψ close to 0); a dry sponge 
    clings to the last drops with enormous force (ψ << 0).

    Equations implemented:
      REW      = (stock - residual) / (saturation - residual)  [Eq. 22]
      k_soil   = Ksat × B_GC × REW^I × (1-(1-REW^(1/m))^m)²    [Eq. 21 variant]
      psi_soil = -((1/REW)^(1/m) - 1)^(1/n) / (α × 10000)      [Eq. 48]
    """

    # Eq 22 ---------------------------------------------------------------------
    # Eq 22 determines how much water there is in the soil
    # Van Genuchten formulation to generate hourly soil forcings from daily
    # climatic variables.

    # V_saturation_capacity indicates how much water the soil can hold
    # V_residual_capacity indicates how much water is trapped in the soil that 
    # roots can't acess
    max_water = params.V_saturation_capacity - params.V_residual_capacity

    # eff_water indicates how much usable water remains 
    eff_water = soil.soil_water_stock - params.V_residual_capacity

    # REW only counts the usable water
    # Ratio: 0 means "dry soil" (only residual left), 1 means "soil fully
    # saturated" The np.clip prevents REW from hitting exactly 0 (which would
    # cause division-by-zero in the next steps) or exceeding 1.
    REW = np.clip(eff_water / max_water, 0.0001, 1.0)
    soil.REW = REW

    # Soil hydraulic conductance ------------------------------------------------
    # How easily water flows through the soil at a given moisture level.

    # The relationship between moisture and conductivity is extremely nonlinear:
    # losing half your water might reduce conductivity by 99%.

    # REW**params.I_vg = accounts for the fact that water doesn't flow in
    # straight lines through soil — it follows tortuous paths around soil
    # particles

    # When REW = 1: this equals 1 (no penalty).
    # When REW = 0.5 and I = 0.5: this equals 0.5^0.5 ≈ 0.71 (moderate penalty).

    # (1 - (1 - REW ** (1/m)) ** m) ** 2 = This is the pore-connectivity factor.
    # It captures the idea that as soil dries, the remaining water-filled pores
    # become disconnected. Remember m = 1 − 1/n, where n is the van Genuchten
    # shape parameter that controls how steep the retention curve is.

    # The inner part (1 - REW^(1/m))^m gives you the fraction of pores that are
    # NOT contributing to flow.
    # When REW = 1: this whole term equals 1.
    # When REW → 0: this term → 0.

    # k_temp is a relative conductance (0 to 1)
    k_temp = REW**params.I_vg * (1 - (1 - REW ** (1 / params.m)) ** params.m) ** 2

    # params.Ksat: the saturated hydraulic conductivity

    # params.B_GC: the Gardner-Cowan scaling factor from Equation 21 in the paper.
    # This accounts for root geometry, how close the roots are packed and how
    # thick the soil layer is.
    # More roots packed closer together equals shorter flow path from soil to
    # root therefore a higher conductance.
    soil.k_soil = 1000 * params.Ksat * params.B_GC * k_temp

    # Calculate Soil water potential --------------------------------------------
    # Equation 48 from the paper
    # Imagine squeezing water out of a sponge. When the sponge is soaking wet
    # (REW ≈ 1), you barely need to squeeze, water drips out easily.
    # The "suction" the sponge exerts on its remaining water is almost zero
    # (ψ ≈ 0). As you squeeze out more water (REW decreasing), the remaining
    # water is held more and more tightly in the smallest pores. You need to
    # squeeze harder and harder (ψ becomes more negative). When the sponge is
    # nearly dry (REW → 0), ψ → −∞.

    soil.psi_soil = (
        -(((1 / REW) ** (1 / params.m) - 1) ** (1 / params.n_vg))
        / params.alpha_vg
        / 10000
        - params.offset_psoil
    )

    # Diagnostics ---------------------------------------------------------------
    # Not used by the sureau_solver, but useful for diagnostics and output
    soil.RWC = np.sum(eff_water) / np.sum(max_water)
    max_fc = params.V_field_capacity - params.V_residual_capacity
    max_wp = params.V_field_capacity - params.V_wilting_point
    eff_wp = soil.soil_water_stock - params.V_wilting_point
    soil.REW_tot = np.sum(eff_water) / np.sum(max_fc)
    soil.REW_wp = np.sum(eff_wp) / np.sum(max_wp)

    return soil

# %% ../nbs/203_sureau_soil_hydraulics.ipynb #dd8a365a
def compute_soil_Campbell(soil: SurEauSoil, params: SurEauSoilParams) -> SurEauSoil:
    """Campbell kSoil and PsiSoil using a ower-law relationships
    ψ = ψ_e × (θ/θ_s)^(−b)
    K = K_sat × (θ/θ_s)^(2b+3)

    Transform soil moisture into water potential and k conductance
    """

    # Compute the fraction of pore space filled with water
    # Campbell normalises between zero and saturation
    ratio = soil.soil_water_stock / params.V_saturation_capacity

    # Compute Soil hydraulic conductance ----------------------------------------
    soil.k_soil = ratio ** (-params.b_camp * 2 + 2)

    # Compute Soil water potential ----------------------------------------------
    # ψ = −ψe × (θ/θs)^(−b)
    # ψe represents how hard you have to squeeze before any water comes out
    # (air-entry).
    #
    # b represents how rapidly the squeeze force ramps up as you compress more
    # water.
    # A large b (like clay, b ≈ 10) means the force ramps up steeply — the
    # remaining water is gripped hard. A small b (like sand, b ≈ 2) means a
    # gentler ramp — water flows out more evenly.
    soil.psi_soil = (
        -params.psie_camp * (ratio ** (-params.b_camp)) - params.offset_psoil
    )

    # Diagnostics ---------------------------------------------------------------
    # Not used by the sureau_solver, but useful for diagnostics and output
    max_water = params.V_saturation_capacity - params.V_residual_capacity
    eff_water = soil.soil_water_stock - params.V_residual_capacity
    REW = np.clip(eff_water / max_water, 0.0001, 1.0)
    soil.REW = REW
    soil.RWC = np.sum(eff_water) / np.sum(max_water)
    max_fc = params.V_field_capacity - params.V_residual_capacity
    max_wp = params.V_field_capacity - params.V_wilting_point
    eff_wp = soil.soil_water_stock - params.V_wilting_point
    soil.REW_tot = np.sum(eff_water) / np.sum(max_fc)
    soil.REW_wp = np.sum(eff_wp) / np.sum(max_wp)

    return soil

# %% ../nbs/203_sureau_soil_hydraulics.ipynb #d7582939
def compute_soil_conductance_and_psi(
    soil: SurEauSoil, params: SurEauSoilParams
) -> SurEauSoil:
    """Dispatch to VG or Campbell."""

    if params.PTF == "VG":
        return compute_soil_VG(soil, params)

    elif params.PTF == "Campbell":
        return compute_soil_Campbell(soil, params)

    raise ValueError(f"Unknown PTF: {params.PTF}")

# %% ../nbs/203_sureau_soil_hydraulics.ipynb #28f04412
def compute_infiltration(
    soil: SurEauSoil, params: SurEauSoilParams, ppt_soil, cst_infil=0.7
) -> SurEauSoil:
    """Infiltration through soil layers, then update psi/k.

    ANALOGY — Stacked Buckets:
   
    Picture 3 buckets stacked on top of each other, each with a small
    hole at the bottom.

    Phase 1 Percolation (slow drip):
      Before rain arrives, any bucket already above its "comfortable full"
      line (field capacity) slowly drips into the one below.

      The cst_infil parameter (0.7) means 70% of the excess drips per
      timestep, not everything at once, like a slow leak.

    Phase 2 Add rainfall:
      Pour the rain into the top bucket.

    Phase 3 Surcharge (overflow):
      If any bucket is now above its absolute maximum (saturation), the
      excess instantly spills into the bucket below.  The bottom bucket's
      overflow becomes deep drainage — water lost from the system.
    """

    n = params.n_layers

    # IMPORTANT: .copy() to not mutate original
    SWS = soil.soil_water_stock.copy()
    percolation = np.zeros(n)
    surcharge = np.zeros(n)

    # Percolation ---------------------------------------------------------------
    # Free, low drainage from field capacity, before rain arrives
    #
    # Before the rain even starts, check if any bucket is already above its
    # "comfortable full" line from yesterday. If so, some water slowly drips
    # down.

    # Loop through each soil layer from top to bottom.
    for each_layer_i in range(n):
        # If the water in this layer exceeds field capacity...
        if SWS[each_layer_i] > params.V_field_capacity[each_layer_i]:
            # The cst_infil parameter smooths the drainage.
            # It prevents all excess water from vanishing instantly.
            # Think of it as the sponge releasing 70% of its drip-water per
            # timestep, not all of it at once.

            percolation[each_layer_i] = cst_infil * (
                SWS[each_layer_i] - params.V_field_capacity[each_layer_i]
            )

            # Remove that percolation from the current layer.
            SWS[each_layer_i] -= percolation[each_layer_i]

            # If there's a layer below, add the percolation to the next layer
            # down.
            #
            # If it's the bottom layer, the water just accumulates in
            # percolation [n-1] and will become deep drainage later.

            if each_layer_i < n - 1:
                SWS[each_layer_i + 1] += percolation[each_layer_i]

    # Add precipitation to top layer
    SWS[0] += ppt_soil

    # Surcharge -----------------------------------------------------------------
    # Overflow from saturation capacity, instantaneous overflow from saturation

    # Loop through each soil layer from top to bottom.
    for each_layer_i in range(n):
        # If the water exceeds saturation capacity..
        if SWS[each_layer_i] > params.V_saturation_capacity[each_layer_i]:
            # Calculate the overflow, all excess water
            surcharge[each_layer_i] = (
                SWS[each_layer_i] - params.V_saturation_capacity[each_layer_i]
            )

            # Cap the layer at saturation capacity
            SWS[each_layer_i] = params.V_saturation_capacity[each_layer_i]

            # If there's a layer below, pour the overflow into it
            if each_layer_i < n - 1:
                SWS[each_layer_i + 1] += surcharge[each_layer_i]

    # Save results and compute derived quantities -------------------------------
    soil.soil_water_stock = SWS
    soil.drainage = percolation[-1] + surcharge[-1]
    soil = compute_soil_conductance_and_psi(soil, params)

    return soil

# %% ../nbs/203_sureau_soil_hydraulics.ipynb #2a9d3551
def update_soil_water(
    soil: SurEauSoil, params: SurEauSoilParams, flux_evap
) -> SurEauSoil:
    """Subtract transpiration flux from soil and update.
    """
    soil.soil_water_stock -= flux_evap
    soil = compute_soil_conductance_and_psi(soil, params)
    return soil

# %% ../nbs/203_sureau_soil_hydraulics.ipynb #a8ad415e
def set_SWC_to_field_capacity(
    soil: SurEauSoil, params: SurEauSoilParams, layers=None
) -> SurEauSoil:
    """Reset soil water stock to field capacity.

    ANALOGY — Refilling the Sponge:

    After a long rainy spell, the soil drains freely until each layer
    reaches its "comfortable full" level — field capacity.  This function
    is the equivalent of saying "pretend it just rained enough to fill
    the sponge back to its comfortable level."
    """

    if layers is not None and len(layers) > 0:
        soil.soil_water_stock[layers] = params.V_field_capacity[layers]

    else:
        soil.soil_water_stock = params.V_field_capacity.copy()
    soil = compute_soil_conductance_and_psi(soil, params)

    return soil

# %% ../nbs/203_sureau_soil_hydraulics.ipynb #8521f0c2
def compute_evaporation(
    soil: SurEauSoil, params: SurEauSoilParams, T_air, RH_air, N_hours
) -> SurEauSoil:
    """Soil surface evaporation 
    
    Equation 35: E_soil = g_soil0 × REW₁ × VPD / P_atm
    
    Only the TOP bucket loses water to the atmosphere directly. How fast
    it dries depends on:
    
      - How dry the air is (VPD — the "thirst" of the atmosphere)
      - How wet the top layer still is (REW₁ — a self-limiting brake)
      - How breathable the soil surface is (g_soil0)

    On a hot dry day with wet topsoil: evaporation is high.
    On a humid day with dry topsoil: evaporation is negligible.
    """

    # Define Soil temperature ---------------------------------------------------
    # soil temperature is about 60% of air temperature plus a 3.59°C offset.
    # Important because VPD depends on temperature. The saturation vapor
    # pressure at the soil surface (which drives evaporation) is set by the soil
    # temperature, not the air temperature.
    T_soil = 0.6009 * T_air + 3.59

    # Compute soil VPD ----------------------------------------------------------
    # Computed at the soil temperature
    VPD_soil = compute_VPD(RH_air, T_soil)

    # Compute Soil evaporation --------------------------------------------------

    # Frozen soil check
    if T_soil < 0:
        soil.evaporation = 0.0

    else:
        # VPD-limited evaporation rate (Equation 35)
        # Equation 35: E_soil = g_soil0 × REW₁ × VPD / P_atm

        # g_soil0 (mmol/m²_soil/s): the maximum soil conductance to water vapor.
        # Keep in mind that a sandy soil with big pores has higher g_soil0 than 
        # a clay with tiny pores.

        # REW: Relative extractable water of the first soil layer only. This
        # scales conductance down as the topsoil dries.
        
        # When REW=1 (wet), the full conductance is available.
        
        # When REW=0.1 (dry), only 10% remains.
        
        # As the top layer dries, it self-limits its own evaporation rate.

        # VPD_soil / 101.3: Driving force for evaporation (VPD in kPa) divided by
        # atmospheric pressure (101.3 kPa). This ratio converts the conductance
        # from a molar basis to a flux: it answers "given this conductance and
        # this dryness of the air, how many mmol of water leave per second?"
        E_VPD = params.g_soil0 * soil.REW[0] * VPD_soil / 101.3

        # ETP-limited evaporation rate (µL/m²/s)
        # soil.ETP` arrives in mm. Convert it to mmol/m²/s to compare with E_VPD

        if N_hours > 0:
            ETP_mmol_s = 1e6 * soil.ETP / (3600 * N_hours * 18)

        else:
            print("ETP_mmol_s is 0. Possible bug?")
            ETP_mmol_s = 0.0

        # Scale by REW
        E_ETP = ETP_mmol_s * soil.REW[0]

        # Take the minimum of both limits
        
        # The soil only can dry as fast as the more restrive of the two allows.
        # For example:
        # On a sunny, dry day: both limits are high -> high E_soil.
        # On a sunny, humid day: E_VPD is the bottleneck, air can't take more 
        # water.
        # On a cloudy, dry day: E_ETP is the bottleneck, not enough energy to 
        # vaporize the water in the soil.
        E_soil = min(E_VPD, E_ETP)

        # Convert instantaneous rate to water depth
        # Convert from mmol/m²/s (instantaneous rate) to mm (water depth over
        # the timestep)
        soil.evaporation = flux_leaf_to_stand(E_soil, dt=N_hours, LAI=1.0)

    # Subtract from topsoil and update ------------------------------------------
    soil.soil_water_stock[0] -= soil.evaporation
    soil = compute_soil_conductance_and_psi(soil, params)

    return soil
